begin;
do $test$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();p uuid:=gen_random_uuid();z uuid:=gen_random_uuid();q uuid:=gen_random_uuid();k uuid:=gen_random_uuid();r public.esg_projects;s public.esg_projects;x public.esg_projects;checks integer:=0;
begin
 begin
 insert into auth.users(id) values(a),(b),(p),(z),(q);
 insert into public.profiles(id,display_name,role,approved) values(a,'Student','aluno',false),(b,'Other','aluno',false),(p,'Professional','profissional',true),(z,'Admin','admin',false),(q,'Other admin','admin',false);
 set local role authenticated;perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);
select * into r from public.submit_esg_project(k,'social',' Test project ',' Description ');if r.owner_id<>a or r.title<>'Test project' or r.description<>'Description' or r.status<>'pending' or r.version<>1 or r.reviewed_at is not null then raise exception 'invalid submitted row';end if;checks:=checks+1;
select * into s from public.submit_esg_project(k,'social','Test project','Description');if s.id<>r.id or (select count(*) from public.esg_projects)<>1 then raise exception 'duplicate';end if;checks:=checks+1;
begin perform public.submit_esg_project(k,'social','Other','Description');raise exception 'unexpected permitted operation';exception when unique_violation then checks:=checks+1;end;
begin perform public.submit_esg_project(gen_random_uuid(),'invalid','Title','Body');raise exception 'unexpected permitted operation';exception when invalid_parameter_value then checks:=checks+1;end;
begin perform public.submit_esg_project(gen_random_uuid(),'social',' ','Body');raise exception 'unexpected permitted operation';exception when invalid_parameter_value then checks:=checks+1;end;
begin perform public.submit_esg_project(gen_random_uuid(),'social','Title',repeat('x',6001));raise exception 'unexpected permitted operation';exception when invalid_parameter_value then checks:=checks+1;end;
begin perform public.submit_esg_project(null,'social','Title','Body');raise exception 'unexpected permitted operation';exception when invalid_parameter_value then checks:=checks+1;end;
begin insert into public.esg_projects(owner_id,request_id,category,title,description) values(a,k,'social','Title','Body');raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
begin update public.esg_projects set status='approved' where id=r.id;raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
begin delete from public.esg_projects where id=r.id;raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
begin perform public.review_esg_project(r.id,1,'approved','Self');raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
perform set_config('request.jwt.claims',json_build_object('sub',b,'is_anonymous',false,'user_metadata',json_build_object('role','admin'))::text,true);
if exists(select 1 from public.esg_projects) then raise exception 'foreign project readable';end if;checks:=checks+1;
begin perform public.review_esg_project(r.id,1,'approved','Metadata escalation');raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
select * into s from public.submit_esg_project(k,'ambiental','Other project','Body');if s.owner_id<>b or s.id=r.id then raise exception 'owner request namespace';end if;checks:=checks+1;
perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
select * into x from public.submit_esg_project(gen_random_uuid(),'economica','Professional project','Body');if x.owner_id<>p then raise exception 'professional submit';end if;checks:=checks+1;
perform set_config('request.jwt.claims',json_build_object('sub',z,'is_anonymous',false)::text,true);
if (select count(*) from public.esg_projects)<>3 then raise exception 'admin queue';end if;checks:=checks+1;
begin perform public.submit_esg_project(gen_random_uuid(),'social','Admin project','Body');raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
begin perform public.review_esg_project(r.id,99,'approved','Reason');raise exception 'unexpected permitted operation';exception when invalid_parameter_value then checks:=checks+1;end;
begin perform public.review_esg_project(r.id,1,'approved',' ');raise exception 'unexpected permitted operation';exception when invalid_parameter_value then checks:=checks+1;end;
begin perform public.review_esg_project(gen_random_uuid(),1,'approved','Reason');raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
select * into r from public.review_esg_project(r.id,1,'approved',' Evidence checked ');if r.status<>'approved' or r.version<>2 or r.review_reason<>'Evidence checked' then raise exception 'review failed';end if;checks:=checks+1;
if not exists(select 1 from public.esg_project_reviews where project_id=r.id and reviewer_id=z and reviewed_version=1 and decision='approved' and reason='Evidence checked') then raise exception 'audit missing';end if;checks:=checks+1;
perform public.review_esg_project(r.id,1,'approved','Evidence checked');if (select count(*) from public.esg_project_reviews)<>1 then raise exception 'duplicate review';end if;checks:=checks+1;
begin perform public.review_esg_project(r.id,1,'rejected','Changed mind');raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
begin update public.esg_project_reviews set reason='rewrite' where project_id=r.id;raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
begin delete from public.esg_project_reviews where project_id=r.id;raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
select * into s from public.review_esg_project(s.id,1,'rejected','Needs evidence');if s.status<>'rejected' or s.version<>2 then raise exception 'reject failed';end if;checks:=checks+1;
perform set_config('request.jwt.claims',json_build_object('sub',q,'is_anonymous',false)::text,true);
begin perform public.review_esg_project(r.id,1,'approved','Evidence checked');raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);
if (select count(*) from public.esg_project_reviews)<>1 then raise exception 'own decision visibility';end if;checks:=checks+1;
select * into r from public.submit_esg_project(k,'social','Test project','Description');if r.status<>'approved' then raise exception 'replay after decision';end if;checks:=checks+1;
reset role;update public.profiles set role='admin' where id=p;set local role authenticated;perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
begin perform public.review_esg_project(x.id,1,'approved','Self after promotion');raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
perform set_config('request.jwt.claims',json_build_object('sub',z,'is_anonymous',true)::text,true);
if exists(select 1 from public.esg_projects) or exists(select 1 from public.esg_project_reviews) then raise exception 'anonymous Auth reads';end if;checks:=checks+1;
begin perform public.review_esg_project(x.id,1,'approved','Anonymous admin');raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
begin perform public.submit_esg_project(gen_random_uuid(),'social','Title','Body');raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
set local role anon;
begin select count(*) from public.esg_projects;raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
begin perform public.submit_esg_project(gen_random_uuid(),'social','Title','Body');raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
set local role service_role;
begin update public.esg_projects set title='Bypass' where id=r.id;raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
begin perform public.review_esg_project(x.id,1,'approved','Service bypass');raise exception 'unexpected permitted operation';exception when insufficient_privilege then checks:=checks+1;end;
reset role;if checks<>38 then raise exception 'wrong check count %',checks;end if;
raise sqlstate 'W3691' using message='38 ESG checks passed; rollback fixtures';
exception when sqlstate 'W3691' then null;end;
end $test$;
rollback;
