begin;
do $test$
declare p uuid:=gen_random_uuid();other uuid:=gen_random_uuid();s uuid:=gen_random_uuid();a uuid:=gen_random_uuid();d date:=(now() at time zone 'America/Sao_Paulo')::date+1;m date:=date_trunc('month',(now() at time zone 'America/Sao_Paulo')::date+1)::date;r public.professional_availability_days;checks integer:=0;
begin
 begin
 insert into auth.users(id) values(p),(other),(s),(a);
 insert into public.profiles(id,display_name,role,approved) values(p,'Agenda pro','profissional',true),(other,'Other pro','profissional',true),(s,'Student','aluno',false),(a,'Admin','admin',false);
 set local role authenticated;perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
 select * into r from public.save_professional_availability(d,0,array[23,5,12]::smallint[],false);
 if r.professional_id<>p or r.version<>1 or r.available_hours<>array[5,12,23]::smallint[] or r.released then raise exception 'draft ownership';end if;checks:=checks+1;
 if (select count(*) from public.professional_availability_days)<>1 then raise exception 'own read';end if;checks:=checks+1;
 begin perform public.save_professional_availability(d,0,array[5]::smallint[],false);raise exception 'stale insert';exception when serialization_failure then checks:=checks+1;end;
 begin perform public.save_professional_availability(d,1,array[5,5]::smallint[],false);raise exception 'duplicate hours';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.save_professional_availability(d,1,array[4]::smallint[],false);raise exception 'early hour';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.save_professional_availability(d,1,array[24]::smallint[],false);raise exception 'late hour';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.save_professional_availability(d,1,array[null]::smallint[],false);raise exception 'null hour';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.save_professional_availability(d,1,'{}'::smallint[],true);raise exception 'release empty';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.save_professional_availability(d-2,0,array[5]::smallint[],true);raise exception 'past day';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.save_professional_availability(d+366,0,array[5]::smallint[],true);raise exception 'far future';exception when invalid_parameter_value then checks:=checks+1;end;
 begin update public.professional_availability_days set released=true;raise exception 'direct update';exception when insufficient_privilege then checks:=checks+1;end;
 begin insert into public.professional_availability_days(professional_id,day) values(p,d+1);raise exception 'direct insert';exception when insufficient_privilege then checks:=checks+1;end;
 begin delete from public.professional_availability_days;raise exception 'direct delete';exception when insufficient_privilege then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',false,'user_metadata',json_build_object('role','profissional','approved',true))::text,true);
 if exists(select 1 from public.professional_availability_days) or exists(select 1 from public.list_released_availability(p,m)) then raise exception 'student draft visibility';end if;checks:=checks+1;
 begin perform public.save_professional_availability(d,0,array[5]::smallint[],true);raise exception 'student creates';exception when insufficient_privilege then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
 select * into r from public.save_professional_availability(d,1,array[5,23]::smallint[],true);
 if r.version<>2 or not r.released then raise exception 'release';end if;checks:=checks+1;
 begin perform public.save_professional_availability(d,1,array[5]::smallint[],false);raise exception 'stale update';exception when serialization_failure then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',false)::text,true);
 if not exists(select 1 from public.list_released_availability(p,m) x where x.day=d and x.available_hours=array[5,23]::smallint[]) then raise exception 'released visibility';end if;checks:=checks+1;
 begin perform public.list_released_availability(p,m+1);raise exception 'invalid month';exception when invalid_parameter_value then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',other,'is_anonymous',false)::text,true);
 if exists(select 1 from public.professional_availability_days) then raise exception 'other pro read';end if;checks:=checks+1;
 begin perform public.list_released_availability(p,m);raise exception 'pro directory access';exception when insufficient_privilege then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);
 if exists(select 1 from public.professional_availability_days) then raise exception 'admin read';end if;checks:=checks+1;
 begin perform public.save_professional_availability(d,0,array[5]::smallint[],true);raise exception 'admin creates';exception when insufficient_privilege then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',true)::text,true);
 if exists(select 1 from public.professional_availability_days) then raise exception 'anonymous read';end if;checks:=checks+1;
 begin perform public.save_professional_availability(d,2,array[5]::smallint[],false);raise exception 'anonymous save';exception when insufficient_privilege then checks:=checks+1;end;
 set local role anon;begin perform public.list_released_availability(p,m);raise exception 'anon executes';exception when insufficient_privilege then checks:=checks+1;end;
 set local role service_role;begin update public.professional_availability_days set released=false;raise exception 'service direct edit';exception when insufficient_privilege then checks:=checks+1;end;
 reset role;update public.profiles set approved=false where id=p;
 set local role authenticated;perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',false)::text,true);
 if exists(select 1 from public.list_released_availability(p,m)) then raise exception 'unapproved visibility';end if;checks:=checks+1;
 perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
 begin perform public.save_professional_availability(d,2,array[5]::smallint[],false);raise exception 'unapproved save';exception when insufficient_privilege then checks:=checks+1;end;
 reset role;update public.profiles set approved=true where id=p;
 set local role authenticated;perform public.save_professional_availability(d,2,'{}'::smallint[],false);
 perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',false)::text,true);
 if exists(select 1 from public.list_released_availability(p,m)) then raise exception 'withdrawn day visible';end if;checks:=checks+1;
 perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
 perform public.save_professional_availability(d-1,0,array[5,23]::smallint[],true);
 perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',false)::text,true);
 if exists(select 1 from public.list_released_availability(p,date_trunc('month',d-1)::date) x cross join lateral unnest(x.available_hours) h where x.day=d-1 and h<=extract(hour from now() at time zone 'America/Sao_Paulo')) then raise exception 'past hours visible';end if;checks:=checks+1;
 reset role;if checks<>31 then raise exception 'unexpected checks %',checks;end if;
 raise sqlstate 'W3691' using message='31 availability checks passed; rollback fixtures';
 exception when sqlstate 'W3691' then null;
 end;
end $test$;
rollback;
