begin;
do $test$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); p uuid:=gen_random_uuid(); z uuid:=gen_random_uuid(); r public.professional_applications; checks integer:=0;
begin
 begin
  insert into auth.users(id) values(a),(b),(p),(z);
  insert into public.profiles(id,display_name,role,approved) values(a,'Applicant','aluno',false),(b,'Other applicant','aluno',false),(p,'Approved professional','profissional',true),(z,'Administrator','admin',false);
  set local role authenticated;perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false,'user_metadata',json_build_object('role','admin'))::text,true);
  select * into r from public.submit_professional_application('educacao_fisica',' Fixture credential ');
  if r.applicant_id<>a or r.applicant_name<>'Applicant' or r.status<>'pending' or r.version<>1 or r.credential<>'Fixture credential' then raise exception 'submission incorrect';end if;checks:=checks+1;
  if not exists(select 1 from public.profiles where id=a and role='aluno' and not approved) then raise exception 'self promotion happened';end if;checks:=checks+1;
  perform public.submit_professional_application('educacao_fisica','Fixture credential');if (select count(*) from public.professional_applications)<>1 then raise exception 'duplicate request';end if;checks:=checks+1;
  begin perform public.submit_professional_application('nutricao','Other');raise exception 'pending edit permitted';exception when unique_violation then checks:=checks+1;end;
  begin perform public.review_professional_application(a,1,'approved','Fake admin metadata');raise exception 'self review permitted';exception when insufficient_privilege then checks:=checks+1;end;
  begin update public.profiles set role='admin',approved=true where id=a;raise exception 'direct promotion permitted';exception when insufficient_privilege then checks:=checks+1;end;
  begin insert into public.professional_applications(applicant_id,applicant_name,specialty,credential) values(b,'Other','nutricao','Fixture');raise exception 'direct insert permitted';exception when insufficient_privilege then checks:=checks+1;end;
  begin update public.professional_applications set status='approved' where applicant_id=a;raise exception 'direct update permitted';exception when insufficient_privilege then checks:=checks+1;end;
  begin delete from public.professional_applications where applicant_id=a;raise exception 'direct delete permitted';exception when insufficient_privilege then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',b,'is_anonymous',false,'user_metadata',json_build_object('role','admin'))::text,true);
  if exists(select 1 from public.professional_applications) then raise exception 'other applicant reads credentials';end if;checks:=checks+1;
  begin perform public.review_professional_application(a,1,'approved','Fake metadata admin');raise exception 'metadata admin reviewed';exception when insufficient_privilege then checks:=checks+1;end;
  begin perform public.submit_professional_application('unknown','Fixture');raise exception 'invalid specialty';exception when invalid_parameter_value then checks:=checks+1;end;
  begin perform public.submit_professional_application('nutricao',' ');raise exception 'empty credential';exception when invalid_parameter_value then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
  begin perform public.submit_professional_application('nutricao','Fixture');raise exception 'approved professional resubmitted';exception when insufficient_privilege then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',z,'is_anonymous',false)::text,true);
  if not exists(select 1 from public.professional_applications where applicant_id=a) then raise exception 'admin cannot read queue';end if;checks:=checks+1;
  begin perform public.review_professional_application(a,99,'approved','Checked');raise exception 'stale review';exception when insufficient_privilege then checks:=checks+1;end;
  begin perform public.review_professional_application(a,1,'approved',' ');raise exception 'empty reason';exception when invalid_parameter_value then checks:=checks+1;end;
  select * into r from public.review_professional_application(a,1,'rejected','Insufficient evidence');if r.status<>'rejected' then raise exception 'reject failed';end if;checks:=checks+1;
  if not exists(select 1 from public.professional_application_reviews where applicant_id=a and application_version=1 and decision='rejected' and reviewer_id=z) then raise exception 'review audit missing';end if;checks:=checks+1;
  begin perform public.review_professional_application(a,1,'approved','Repeat');raise exception 'repeat decision accepted';exception when insufficient_privilege then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);
  if not exists(select 1 from public.professional_application_reviews where applicant_id=a) then raise exception 'owner cannot read decision';end if;checks:=checks+1;
  select * into r from public.submit_professional_application('nutricao','Updated fixture');if r.version<>2 or r.status<>'pending' or r.review_reason is not null then raise exception 'resubmit failed';end if;checks:=checks+1;
  perform public.request_student_link(p);
  perform set_config('request.jwt.claims',json_build_object('sub',z,'is_anonymous',false)::text,true);
  begin perform public.review_professional_application(a,2,'approved','Checked');raise exception 'student link orphaned';exception when unique_violation then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);perform public.revoke_student_link(a,1);
  perform set_config('request.jwt.claims',json_build_object('sub',z,'is_anonymous',false)::text,true);
  select * into r from public.review_professional_application(a,2,'approved','Evidence checked');if r.status<>'approved' or (select count(*) from public.professional_application_reviews where applicant_id=a)<>2 then raise exception 'approval or audit failed';end if;checks:=checks+1;
  perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);
  if not exists(select 1 from public.profiles where id=a and role='profissional' and approved) then raise exception 'trusted approval failed';end if;checks:=checks+1;
  begin update public.professional_application_reviews set decision='approved' where applicant_id=a;raise exception 'audit editable';exception when insufficient_privilege then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',b,'is_anonymous',false)::text,true);
  if exists(select 1 from public.professional_application_reviews) then raise exception 'other applicant reads audit';end if;checks:=checks+1;
  perform set_config('request.jwt.claims',json_build_object('sub',b,'is_anonymous',true)::text,true);
  begin perform public.submit_professional_application('nutricao','Fixture');raise exception 'anonymous Auth submits';exception when insufficient_privilege then checks:=checks+1;end;
  if exists(select 1 from public.professional_applications) then raise exception 'anonymous Auth reads';end if;checks:=checks+1;
  set local role anon;
  begin perform public.submit_professional_application('nutricao','Fixture');raise exception 'anon executes';exception when insufficient_privilege then checks:=checks+1;end;
  reset role;if checks<>30 then raise exception 'unexpected checks %',checks;end if;
  raise sqlstate 'W3691' using message='30 application checks passed; rollback fixtures';
 exception when sqlstate 'W3691' then null;
 end;
end $test$;
rollback;
