begin;
do $test$
declare p uuid:=gen_random_uuid();q uuid:=gen_random_uuid();s uuid:=gen_random_uuid();a uuid:=gen_random_uuid();k uuid:=gen_random_uuid();r public.professional_booking_terms;checks integer:=0;
begin
 begin
 insert into auth.users(id) values(p),(q),(s),(a);
 insert into public.profiles(id,display_name,role,approved) values(p,'Terms pro','profissional',true),(q,'Other pro','profissional',true),(s,'Student','aluno',false),(a,'Admin','admin',false);
 set local role authenticated;perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
 select * into r from public.save_professional_booking_terms(k,0,20000,2500,48);
 if r.professional_id<>p or r.version<>1 or r.deposit_cents<>5000 or not r.no_show_deposit_retained or r.created_at is null then raise exception 'quote example';end if;checks:=checks+1;
 perform public.save_professional_booking_terms(k,0,20000,2500,48);if (select count(*) from public.professional_booking_terms)<>1 then raise exception 'retry duplicated';end if;checks:=checks+1;
 begin perform public.save_professional_booking_terms(k,0,20000,3000,48);raise exception 'key conflict';exception when unique_violation then checks:=checks+1;end;
 begin perform public.save_professional_booking_terms(gen_random_uuid(),0,20000,2500,48);raise exception 'stale version';exception when serialization_failure then checks:=checks+1;end;
 select * into r from public.save_professional_booking_terms(gen_random_uuid(),1,101,5000,0);
 if r.version<>2 or r.deposit_cents<>51 then raise exception 'round half cent';end if;checks:=checks+1;
 if not exists(select 1 from public.professional_booking_terms where version=1 and price_cents=20000 and deposit_cents=5000) then raise exception 'old version changed';end if;checks:=checks+1;
 perform public.save_professional_booking_terms(k,0,20000,2500,48);if (select count(*) from public.professional_booking_terms)<>2 then raise exception 'old retry duplicated';end if;checks:=checks+1;
 begin perform public.save_professional_booking_terms(gen_random_uuid(),2,1,1,24);raise exception 'zero rounded deposit';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.save_professional_booking_terms(gen_random_uuid(),2,0,2500,24);raise exception 'zero price';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.save_professional_booking_terms(gen_random_uuid(),2,100,10001,24);raise exception 'over 100 percent';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.save_professional_booking_terms(gen_random_uuid(),2,100,2500,721);raise exception 'cancel limit';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.save_professional_booking_terms(null,2,100,2500,24);raise exception 'null key';exception when invalid_parameter_value then checks:=checks+1;end;
 select * into r from public.save_professional_booking_terms(gen_random_uuid(),2,9007199254740991,10000,720);if r.deposit_cents<>9007199254740991 then raise exception 'overflow';end if;checks:=checks+1;
 begin insert into public.professional_booking_terms(professional_id,request_id,version,price_cents,deposit_basis_points,free_cancel_hours) values(p,gen_random_uuid(),4,100,2500,24);raise exception 'direct insert';exception when insufficient_privilege then checks:=checks+1;end;
 begin update public.professional_booking_terms set price_cents=1;raise exception 'direct update';exception when insufficient_privilege then checks:=checks+1;end;
 begin delete from public.professional_booking_terms;raise exception 'direct delete';exception when insufficient_privilege then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',q,'is_anonymous',false)::text,true);
 if exists(select 1 from public.professional_booking_terms) then raise exception 'other pro history';end if;checks:=checks+1;
 begin perform public.get_professional_booking_terms(p);raise exception 'pro student rpc';exception when insufficient_privilege then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',false,'user_metadata',json_build_object('role','profissional','approved',true))::text,true);
 if exists(select 1 from public.professional_booking_terms) then raise exception 'student history';end if;checks:=checks+1;
 if not exists(select 1 from public.get_professional_booking_terms(p) t where t.version=3 and t.deposit_cents=9007199254740991) then raise exception 'latest terms';end if;checks:=checks+1;
 begin perform public.save_professional_booking_terms(gen_random_uuid(),0,100,2500,24);raise exception 'metadata spoof';exception when insufficient_privilege then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);
 if exists(select 1 from public.professional_booking_terms) then raise exception 'admin global history';end if;checks:=checks+1;
 begin perform public.save_professional_booking_terms(gen_random_uuid(),0,100,2500,24);raise exception 'admin saves';exception when insufficient_privilege then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',true)::text,true);
 if exists(select 1 from public.professional_booking_terms) then raise exception 'anonymous history';end if;checks:=checks+1;
 begin perform public.save_professional_booking_terms(gen_random_uuid(),3,100,2500,24);raise exception 'anonymous saves';exception when insufficient_privilege then checks:=checks+1;end;
 set local role anon;begin perform public.get_professional_booking_terms(p);raise exception 'anon executes';exception when insufficient_privilege then checks:=checks+1;end;
 set local role service_role;begin update public.professional_booking_terms set price_cents=100;raise exception 'service edits';exception when insufficient_privilege then checks:=checks+1;end;
 reset role;update public.profiles set approved=false where id=p;
 set local role authenticated;perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',false)::text,true);
 if exists(select 1 from public.get_professional_booking_terms(p)) then raise exception 'unapproved quote';end if;checks:=checks+1;
 perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
 begin perform public.save_professional_booking_terms(k,0,20000,2500,48);raise exception 'unapproved retry';exception when insufficient_privilege then checks:=checks+1;end;
 reset role;if exists(select 1 from public.wallet_accounts where user_id in(p,q,s,a)) then raise exception 'terms created money';end if;checks:=checks+1;
 if checks<>30 then raise exception 'unexpected checks %',checks;end if;
 raise sqlstate 'W3691' using message='30 booking terms checks passed; rollback fixtures';
 exception when sqlstate 'W3691' then null;
 end;
end $test$;
rollback;
