begin;
do $test$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); p uuid:=gen_random_uuid(); q uuid:=gen_random_uuid(); u uuid:=gen_random_uuid(); legacy uuid:=gen_random_uuid(); z uuid:=gen_random_uuid(); key uuid:=gen_random_uuid(); second_key uuid:=gen_random_uuid(); plan public.training_plans; second_plan public.training_plans; notice public.training_plan_notifications; seen timestamptz; checks integer:=0;
begin
 begin
  insert into auth.users(id) values(a),(b),(p),(q),(u),(legacy),(z);
  insert into public.profiles(id,display_name,role,approved) values(a,'Student A','aluno',false),(b,'Student B','aluno',false),(p,'Professional','profissional',true),(q,'Nutrition','profissional',true),(u,'Unapproved','profissional',false),(legacy,'Legacy','profissional',true),(z,'Admin','admin',false);
  insert into public.professional_applications(applicant_id,applicant_name,specialty,credential,status,reviewed_at,review_reason) values(p,'Professional','educacao_fisica','Fixture','approved',now(),'Fixture verified'),(q,'Nutrition','nutricao','Fixture','approved',now(),'Fixture verified'),(u,'Unapproved','educacao_fisica','Fixture','approved',now(),'Fixture verified');
  set local role authenticated;
  perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);perform public.request_student_link(p);
  perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
  begin perform public.create_training_plan(a,1,key,'Title','Text');raise exception 'pending link permitted';exception when insufficient_privilege then checks:=checks+1;end;
  perform public.accept_student_link(a,1);
  select * into plan from public.create_training_plan(a,1,key,' Title ',' Text ');
  if plan.student_id<>a or plan.professional_id<>p or plan.link_version<>1 or plan.title<>'Title' or plan.content<>'Text' then raise exception 'creation wrong';end if;checks:=checks+1;
  perform public.create_training_plan(a,1,key,'Title','Text');if (select count(*) from public.training_plans)<>1 then raise exception 'duplicate publication';end if;checks:=checks+1;
  begin perform public.create_training_plan(a,1,key,'Different','Text');raise exception 'request key reused';exception when unique_violation then checks:=checks+1;end;
  begin perform public.create_training_plan(a,99,gen_random_uuid(),'Title','Text');raise exception 'stale link created';exception when insufficient_privilege then checks:=checks+1;end;
  begin perform public.create_training_plan(b,1,gen_random_uuid(),'Title','Text');raise exception 'other student created';exception when insufficient_privilege then checks:=checks+1;end;
  begin perform public.create_training_plan(a,1,gen_random_uuid(),' ','Text');raise exception 'blank title created';exception when invalid_parameter_value then checks:=checks+1;end;
  begin perform public.create_training_plan(a,1,gen_random_uuid(),'Title',repeat('X',6001));raise exception 'oversize created';exception when invalid_parameter_value then checks:=checks+1;end;
  if exists(select 1 from public.training_plan_notifications) then raise exception 'professional reads pupil notices';end if;checks:=checks+1;
  begin perform public.read_training_notification(plan.id);raise exception 'professional marked read';exception when insufficient_privilege then checks:=checks+1;end;
  begin insert into public.training_plans(request_id,student_id,professional_id,link_version,title,content) values(gen_random_uuid(),a,p,1,'Fake','Fake');raise exception 'direct insert';exception when insufficient_privilege then checks:=checks+1;end;
  begin update public.training_plans set content='Changed' where id=plan.id;raise exception 'direct update';exception when insufficient_privilege then checks:=checks+1;end;
  begin delete from public.training_plans where id=plan.id;raise exception 'direct delete';exception when insufficient_privilege then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);
  if (select count(*) from public.training_plans)<>1 or (select count(*) from public.training_plan_notifications)<>1 then raise exception 'student plan/notice absent or duplicate';end if;checks:=checks+1;
  select * into notice from public.read_training_notification(plan.id);seen:=notice.read_at;if seen is null or notice.recipient_id<>a then raise exception 'read notice wrong';end if;checks:=checks+1;
  select * into notice from public.read_training_notification(plan.id);if notice.read_at<>seen then raise exception 'repeat read timestamp changed';end if;checks:=checks+1;
  begin update public.training_plan_notifications set read_at=null where plan_id=plan.id;raise exception 'direct notice update';exception when insufficient_privilege then checks:=checks+1;end;
  begin perform public.create_training_plan(a,1,gen_random_uuid(),'Fake','Fake');raise exception 'student creates';exception when insufficient_privilege then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',b,'is_anonymous',false,'user_metadata',json_build_object('role','admin'))::text,true);
  if exists(select 1 from public.training_plans) or exists(select 1 from public.training_plan_notifications) then raise exception 'other student reads';end if;checks:=checks+1;
  begin perform public.read_training_notification(plan.id);raise exception 'other student marks read';exception when insufficient_privilege then checks:=checks+1;end;
  perform public.request_student_link(q);
  perform set_config('request.jwt.claims',json_build_object('sub',q,'is_anonymous',false)::text,true);perform public.accept_student_link(b,1);
  begin perform public.create_training_plan(b,1,gen_random_uuid(),'Title','Text');raise exception 'wrong specialty creates';exception when insufficient_privilege then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',legacy,'is_anonymous',false)::text,true);
  begin perform public.create_training_plan(a,1,gen_random_uuid(),'Title','Text');raise exception 'legacy qualification bypass';exception when insufficient_privilege then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',z,'is_anonymous',false)::text,true);
  if exists(select 1 from public.training_plans) then raise exception 'admin clinical blanket read';end if;checks:=checks+1;
  perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);perform public.revoke_student_link(a,1);
  if exists(select 1 from public.training_plans) or exists(select 1 from public.training_plan_notifications) then raise exception 'revoked read leak';end if;checks:=checks+1;
  begin perform public.read_training_notification(plan.id);raise exception 'revoked marks read';exception when insufficient_privilege then checks:=checks+1;end;
  perform public.request_student_link(p);
  perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);perform public.accept_student_link(a,2);
  if exists(select 1 from public.training_plans) then raise exception 'reopened link resurrects old content';end if;checks:=checks+1;
  select * into second_plan from public.create_training_plan(a,2,second_key,'New title','New text');if (select count(*) from public.training_plans)<>1 or second_plan.link_version<>2 then raise exception 'new version inaccessible';end if;checks:=checks+1;
  reset role;update public.profiles set approved=false where id=p;set local role authenticated;
  if exists(select 1 from public.training_plans) then raise exception 'approval lost pro still reads';end if;checks:=checks+1;
  perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);
  if exists(select 1 from public.training_plans) then raise exception 'approval lost student still reads';end if;checks:=checks+1;
  reset role;update public.profiles set approved=true where id=p;set local role authenticated;
  perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',true)::text,true);
  if exists(select 1 from public.training_plans) or exists(select 1 from public.training_plan_notifications) then raise exception 'anonymous Auth reads';end if;checks:=checks+1;
  set local role anon;
  begin perform public.read_training_notification(second_plan.id);raise exception 'anon executes';exception when insufficient_privilege then checks:=checks+1;end;
  reset role;if checks<>31 then raise exception 'unexpected checks %',checks;end if;
  raise sqlstate 'W3691' using message='31 training checks passed; rollback fixtures';
 exception when sqlstate 'W3691' then null;
 end;
end $test$;
rollback;
