begin;
do $test$
declare p uuid:=gen_random_uuid();s uuid:=gen_random_uuid();a uuid:=gen_random_uuid();d date:=(now() at time zone 'America/Sao_Paulo')::date+3;r record;t public.professional_booking_terms;checks integer:=0;
begin
 begin
 insert into auth.users(id) values(p),(s),(a);
 insert into public.profiles(id,display_name,role,approved) values(p,'Quote pro','profissional',true),(s,'Student','aluno',false),(a,'Admin','admin',false);
 set local role authenticated;perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
 perform public.save_professional_availability(d,0,array[5,23]::smallint[],true);
 perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',false)::text,true);
 begin perform public.quote_booking_slot(p,d,5);raise exception 'quote without terms';exception when no_data_found then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
 select * into t from public.save_professional_booking_terms(gen_random_uuid(),0,20000,2500,48);
 perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',false)::text,true);
 select * into r from public.quote_booking_slot(p,d,5);
 if r.professional_id<>p or r.day<>d or r.hour<>5 or r.terms_id<>t.id or r.terms_version<>1 or r.availability_version<>1 or r.price_cents<>20000 or r.deposit_cents<>5000 or r.balance_cents<>15000 or not r.no_show_deposit_retained then raise exception 'quote contents';end if;checks:=checks+1;
 if r.starts_at<>((d::timestamp+interval '5 hours') at time zone 'America/Sao_Paulo') or r.ends_at-r.starts_at<>interval '1 hour' or r.free_cancel_deadline<>r.starts_at-interval '48 hours' or r.quoted_at<>now() then raise exception 'timezone or deadline';end if;checks:=checks+1;
 select * into r from public.quote_booking_slot(p,d,23);if (r.ends_at at time zone 'America/Sao_Paulo')::date<>d+1 or extract(hour from r.ends_at at time zone 'America/Sao_Paulo')<>0 then raise exception 'midnight end';end if;checks:=checks+1;
 begin perform public.quote_booking_slot(p,d,6);raise exception 'blocked hour';exception when no_data_found then checks:=checks+1;end;
 begin perform public.quote_booking_slot(p,d,24);raise exception 'hour out of range';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.quote_booking_slot(p,d-4,5);raise exception 'past date';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.quote_booking_slot(p,d+364,5);raise exception 'far future';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.quote_booking_slot(null,d,5);raise exception 'null pro';exception when invalid_parameter_value then checks:=checks+1;end;
 begin perform public.quote_booking_slot(gen_random_uuid(),d,5);raise exception 'unknown pro';exception when no_data_found then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
 select * into t from public.save_professional_booking_terms(gen_random_uuid(),1,101,5000,0);
 perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',false)::text,true);
 select * into r from public.quote_booking_slot(p,d,5);if r.terms_id<>t.id or r.terms_version<>2 or r.deposit_cents<>51 or r.balance_cents<>50 or r.free_cancel_deadline is not null then raise exception 'latest terms rounding no free window';end if;checks:=checks+1;
 perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
 perform public.save_professional_availability(d,1,array[5,23]::smallint[],false);
 perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',false)::text,true);
 begin perform public.quote_booking_slot(p,d,5);raise exception 'unreleased day';exception when no_data_found then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',p,'is_anonymous',false)::text,true);
 perform public.save_professional_availability(d,2,array[5]::smallint[],true);
 begin perform public.quote_booking_slot(p,d,5);raise exception 'professional quotes';exception when insufficient_privilege then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);
 begin perform public.quote_booking_slot(p,d,5);raise exception 'admin quotes';exception when insufficient_privilege then checks:=checks+1;end;
 perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',true)::text,true);
 begin perform public.quote_booking_slot(p,d,5);raise exception 'anonymous quotes';exception when insufficient_privilege then checks:=checks+1;end;
 set local role anon;begin perform public.quote_booking_slot(p,d,5);raise exception 'anon executes';exception when insufficient_privilege then checks:=checks+1;end;
 set local role service_role;begin perform public.quote_booking_slot(p,d,5);raise exception 'service executes';exception when insufficient_privilege then checks:=checks+1;end;
 reset role;update public.profiles set approved=false where id=p;
 set local role authenticated;perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',false)::text,true);
 begin perform public.quote_booking_slot(p,d,5);raise exception 'unapproved quote';exception when no_data_found then checks:=checks+1;end;
 reset role;update public.profiles set approved=true,display_name='' where id=p;
 set local role authenticated;begin perform public.quote_booking_slot(p,d,5);raise exception 'hidden pro quote';exception when no_data_found then checks:=checks+1;end;
 reset role;update public.profiles set display_name='Quote pro' where id=p;
 set local role authenticated;perform set_config('request.jwt.claims',json_build_object('sub',s,'is_anonymous',false,'user_metadata',json_build_object('role','admin'))::text,true);
 select * into r from public.quote_booking_slot(p,d,5);if r.availability_version<>3 then raise exception 'fresh availability version';end if;checks:=checks+1;
 reset role;if exists(select 1 from public.wallet_accounts where user_id in(p,s,a)) or (select count(*) from public.professional_booking_terms where professional_id=p)<>2 or (select version from public.professional_availability_days where professional_id=p and day=d)<>3 then raise exception 'quote has side effects';end if;checks:=checks+1;
 if checks<>21 then raise exception 'unexpected checks %',checks;end if;
 raise sqlstate 'W3691' using message='21 booking quote checks passed; rollback fixtures';
 exception when sqlstate 'W3691' then null;
 end;
end $test$;
rollback;
