begin;
do $test$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();z uuid:=gen_random_uuid();missing uuid:=gen_random_uuid();key1 uuid:=gen_random_uuid();key2 uuid:=gen_random_uuid();w public.wallet_accounts;r public.wallet_withdrawals;r2 public.wallet_withdrawals;checks integer:=0;v bigint;
begin
 begin
  insert into auth.users(id) values(a),(b),(z),(missing);
  insert into public.profiles(id,display_name,role) values(a,'Wallet fixture','aluno'),(b,'Other fixture','aluno'),(z,'Admin fixture','admin');
  set local role authenticated;perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);
  select * into w from public.ensure_wallet_account();if w.user_id<>a or w.available_cents<>0 or w.reserved_cents<>0 then raise exception 'opening balance';end if;checks:=checks+1;
  perform public.ensure_wallet_account();if (select count(*) from public.wallet_accounts)<>1 then raise exception 'duplicate account';end if;checks:=checks+1;
  begin perform public.reserve_wallet_withdrawal(key1,1);raise exception 'unfunded reservation';exception when invalid_parameter_value then checks:=checks+1;end;
  if exists(select 1 from public.wallet_withdrawals) or exists(select 1 from public.wallet_reservation_events) then raise exception 'failed request persisted';end if;checks:=checks+1;
  reset role;update public.wallet_accounts set available_cents=10000 where user_id=a;set local role authenticated;
  select * into r from public.reserve_wallet_withdrawal(key1,4000);
  select * into w from public.wallet_accounts where user_id=a;if w.available_cents<>6000 or w.reserved_cents<>4000 or r.user_id<>a or r.status<>'reserved' then raise exception 'reserve balances';end if;checks:=checks+1;
  perform public.reserve_wallet_withdrawal(key1,4000);if (select count(*) from public.wallet_withdrawals)<>1 or (select count(*) from public.wallet_reservation_events)<>1 then raise exception 'duplicate request';end if;checks:=checks+1;
  begin perform public.reserve_wallet_withdrawal(key1,5000);raise exception 'key conflict';exception when unique_violation then checks:=checks+1;end;
  begin perform public.reserve_wallet_withdrawal(key2,7000);raise exception 'pending reserve not deducted';exception when invalid_parameter_value then checks:=checks+1;end;
  select * into r2 from public.reserve_wallet_withdrawal(key2,6000);select * into w from public.wallet_accounts where user_id=a;if w.available_cents<>0 or w.reserved_cents<>10000 then raise exception 'second request';end if;checks:=checks+1;
  begin perform public.reserve_wallet_withdrawal(gen_random_uuid(),1);raise exception 'overdraw';exception when invalid_parameter_value then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',b,'is_anonymous',false,'user_metadata',json_build_object('role','admin'))::text,true);
  if exists(select 1 from public.wallet_accounts) or exists(select 1 from public.wallet_withdrawals) or exists(select 1 from public.wallet_reservation_events) then raise exception 'other account reads';end if;checks:=checks+1;
  begin perform public.cancel_wallet_withdrawal(r.id);raise exception 'other account cancels';exception when insufficient_privilege then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',z,'is_anonymous',false)::text,true);
  if exists(select 1 from public.wallet_accounts) or exists(select 1 from public.wallet_withdrawals) or exists(select 1 from public.wallet_reservation_events) then raise exception 'admin global read';end if;checks:=checks+1;
  begin perform public.cancel_wallet_withdrawal(r.id);raise exception 'admin cancels other';exception when insufficient_privilege then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);
  begin update public.wallet_accounts set available_cents=100000 where user_id=a;raise exception 'balance client edit';exception when insufficient_privilege then checks:=checks+1;end;
  begin insert into public.wallet_accounts(user_id) values(b);raise exception 'account client insert';exception when insufficient_privilege then checks:=checks+1;end;
  begin insert into public.wallet_withdrawals(user_id,request_id,amount_cents) values(a,gen_random_uuid(),1);raise exception 'withdraw client insert';exception when insufficient_privilege then checks:=checks+1;end;
  begin update public.wallet_withdrawals set status='cancelled',cancelled_at=now() where id=r.id;raise exception 'withdraw client edit';exception when insufficient_privilege then checks:=checks+1;end;
  begin delete from public.wallet_reservation_events where user_id=a;raise exception 'audit delete';exception when insufficient_privilege then checks:=checks+1;end;
  set local role service_role;
  begin update public.wallet_accounts set available_cents=100000 where user_id=a;raise exception 'service direct balance edit';exception when insufficient_privilege then checks:=checks+1;end;
  set local role authenticated;
  perform public.cancel_wallet_withdrawal(r.id);select * into w from public.wallet_accounts where user_id=a;v:=w.version;if w.available_cents<>4000 or w.reserved_cents<>6000 then raise exception 'cancel balances';end if;checks:=checks+1;
  perform public.cancel_wallet_withdrawal(r.id);select * into w from public.wallet_accounts where user_id=a;if w.version<>v or (select count(*) from public.wallet_reservation_events where withdrawal_id=r.id)<>2 then raise exception 'duplicate cancel';end if;checks:=checks+1;
  select * into r from public.reserve_wallet_withdrawal(key1,4000);if r.status<>'cancelled' or (select version from public.wallet_accounts where user_id=a)<>v then raise exception 'retry reopened cancelled';end if;checks:=checks+1;
  perform public.cancel_wallet_withdrawal(r2.id);select * into w from public.wallet_accounts where user_id=a;if w.available_cents<>10000 or w.reserved_cents<>0 then raise exception 'restore balances';end if;checks:=checks+1;
  if (select sum(available_after-available_before) from public.wallet_reservation_events)<>0 or (select sum(reserved_after-reserved_before) from public.wallet_reservation_events)<>0 or (select count(*) from public.wallet_reservation_events)<>4 then raise exception 'audit reconciliation';end if;checks:=checks+1;
  perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',true)::text,true);
  if exists(select 1 from public.wallet_accounts) or exists(select 1 from public.wallet_withdrawals) or exists(select 1 from public.wallet_reservation_events) then raise exception 'anonymous reads';end if;checks:=checks+1;
  begin perform public.ensure_wallet_account();raise exception 'anonymous creates account';exception when insufficient_privilege then checks:=checks+1;end;
  begin perform public.reserve_wallet_withdrawal(gen_random_uuid(),1);raise exception 'anonymous mutation';exception when insufficient_privilege then checks:=checks+1;end;
  set local role anon;begin perform public.ensure_wallet_account();raise exception 'anon executes';exception when insufficient_privilege then checks:=checks+1;end;
  set local role authenticated;perform set_config('request.jwt.claims',json_build_object('sub',missing,'is_anonymous',false)::text,true);
  begin perform public.ensure_wallet_account();raise exception 'missing profile';exception when insufficient_privilege then checks:=checks+1;end;
  perform set_config('request.jwt.claims',json_build_object('sub',a,'is_anonymous',false)::text,true);
  begin perform public.reserve_wallet_withdrawal(null,1);raise exception 'null key';exception when invalid_parameter_value then checks:=checks+1;end;
  begin perform public.reserve_wallet_withdrawal(gen_random_uuid(),0);raise exception 'zero amount';exception when invalid_parameter_value then checks:=checks+1;end;
  reset role;if checks<>32 then raise exception 'unexpected checks %',checks;end if;
  raise sqlstate 'W3691' using message='32 reservation checks passed; rollback fixtures';
 exception when sqlstate 'W3691' then null;
 end;
end $test$;
rollback;
