import {it,expect} from 'vitest'
import {calculateCashbackDistribution as calc} from './cashbackDistribution'
const cents=(n:number)=>Math.round(n*100)
const user=(position:number,extra={})=>({ranking_position:position,role:'profissional',plan:'pro',subscription_status:'ativa',...extra})
function balanced(r:ReturnType<typeof calc>){const individual=r.participants.reduce((s,p)=>s+cents(p.cashbackMonth),0),levels=r.levelsSummary.reduce((s,p)=>s+cents(p.totalDistribuidoNivel),0);expect(individual).toBe(cents(r.totalDistributed));expect(levels).toBe(individual);expect(individual+cents(r.differenceToPool)).toBe(cents(r.pool38));expect(r.participants.every(p=>p.cashbackMonth>=0&&(!p.isExcluded||p.cashbackMonth===0))).toBe(true)}
it('one million official simulation reconciles every cent',()=>{const r=calc(1000000,1023);balanced(r);expect(r.pool38).toBe(380000);expect(r.differenceToPool).toBe(0);expect(r.simulationOnly).toBe(true)})
it('excluded first level cannot become an unreported bonus for last person',()=>{const r=calc(1000,3,[user(1,{plan:'gratis'}),user(2),user(3)]);balanced(r);expect(r.differenceToPool).toBe(139.33);expect(r.totalRedistributed).toBe(0);expect(r.participants[2].cashbackMonth).toBe(108.3)})
it('exclusion redistributes only within its level and updates summary',()=>{const r=calc(1000,3,[user(1),user(2,{isExcluded:true}),user(3)]);balanced(r);expect(r.participants[1].cashbackMonth).toBe(0);expect(r.totalRedistributed).toBeGreaterThan(0);expect(r.differenceToPool).toBe(0)})
it('all excluded preserves entire pool without fabrication',()=>{const r=calc(1000,3,[user(1,{isExcluded:true}),user(2,{isExcluded:true}),user(3,{isExcluded:true})]);balanced(r);expect(r.totalDistributed).toBe(0);expect(r.differenceToPool).toBe(380)})
it('unknown linked professional plan does not become a paid plan',()=>{const r=calc(100,1,[user(1,{role:'aluno',plan:'gratis',linked_professional:'pro'})]);expect(r.totalDistributed).toBe(0);const eligible=calc(100,1,[user(1,{role:'aluno',plan:'gratis',linked_professional:'pro',linked_professional_plan:'premium'})]);expect(eligible.totalDistributed).toBe(38)})
it('missing participants in real mode and missing statuses do not get synthetic awards',()=>{const r=calc(100,3,[user(1,{subscription_status:''})]);balanced(r);expect(r.totalDistributed).toBe(0);expect(r.participants.filter(p=>p.isRealUser)).toHaveLength(1)})
it('invalid amounts volume positions and duplicate inputs fail closed',()=>{for(const base of [-1,NaN,Infinity,1.001,Number.MAX_SAFE_INTEGER])expect(()=>calc(base,1)).toThrow();for(const n of [0,-1,1.5,NaN,500001])expect(()=>calc(100,n)).toThrow();expect(()=>calc(100,3,[user(1),user(1)])).toThrow();expect(()=>calc(100,3,[user(4)])).toThrow()})
it('small pools partial levels and many exclusions preserve nonnegative integer cents',()=>{for(const base of [0,0.01,0.02,0.29,1,10.11,999.99])for(const n of [1,2,3,5,7,31,512,1023])for(const rate of [0,0.5,1])balanced(calc(base,n,[],rate))})
it('full reference population does not truncate participants or summaries',()=>{const r=calc(1000,369371);expect(r.participants).toHaveLength(369371);balanced(r)},15000)
it('identical input returns identical output without mutating records',()=>{const users=[user(1),user(2),user(3)];const before=JSON.stringify(users);expect(calc(10,3,users)).toEqual(calc(10,3,users));expect(JSON.stringify(users)).toBe(before)})
