import {it,expect} from 'vitest'
import {calculateRankingPreview as calc,orderRankingPreview,type RankingPolicy} from './rankingRules'
const policy:RankingPolicy={version:'test-v1',referrals:'minimum_one',partnerServices:'actual',rating:'rounded'}
const facts={id:'a',multiplier:2,completedEligibleServices:10,validatedReferrals:3,rating:4.5,seniorityMonths:12,previousPoints:100,partnerPro:false,joinedAt:'2026-01-01T00:00:00Z'}
it('monthly and accumulated points use only supplied validated service/referral counts',()=>{expect(calc(policy,facts)).toMatchObject({monthlyPoints:75,totalPoints:175,simulationOnly:true});expect(calc(policy,{...facts,validatedReferrals:0}).monthlyPoints).toBe(35)})
it('alternative formulas require explicit policy and version',()=>{expect(calc({...policy,referrals:'plus_one'},facts).monthlyPoints).toBe(95);expect(calc({...policy,referrals:'legacy_divisor_18'},facts).monthlyPoints).toBe(38);expect(()=>calc({...policy,version:''},facts)).toThrow()})
it('floor and ceiling 150 remain distinct explicit choices',()=>{const f={...facts,partnerPro:true,validatedReferrals:1};expect(calc({...policy,partnerServices:'floor_150'},f).monthlyPoints).toBe(315);expect(calc({...policy,partnerServices:'cap_150'},f).monthlyPoints).toBe(35);expect(calc({...policy,partnerServices:'cap_150'},{...f,completedEligibleServices:200}).monthlyPoints).toBe(315)})
it('zero rating is kept rather than replaced with five stars',()=>{expect(calc(policy,{...facts,rating:0}).monthlyPoints).toBe(70)})
it('invalid or overflowing facts cannot produce a score',()=>{for(const change of [{rating:6},{multiplier:4},{validatedReferrals:-1},{previousPoints:Infinity},{completedEligibleServices:1.5},{joinedAt:'bad'},{completedEligibleServices:Number.MAX_SAFE_INTEGER}])expect(()=>calc(policy,{...facts,...change})).toThrow()})
it('deterministic ties keep general positions and reject mixed policies or duplicate users',()=>{const a=calc(policy,facts),b=calc(policy,{...facts,id:'b'});expect(orderRankingPreview([b,a]).map(r=>[r.id,r.position])).toEqual([['a',1],['b',2]]);expect(()=>orderRankingPreview([a,a])).toThrow();expect(()=>orderRankingPreview([a,{...b,rulesVersion:'other'}])).toThrow()})
