import {it,expect} from 'vitest'
import type {SupabaseClient,Session} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {createAccountSession,type AccountState} from './accountSession'
const redirect='https://example.invalid/conta-supabase',password='long-test-password'
function mock(url=redirect){let signedIn=false,id='u1',token='t1',listener:((event:string,session:Session|null)=>void)|undefined,hold:Promise<void>|null=null,fail='',autoSession=false;const calls:{name:string;args?:unknown}[]=[],states:AccountState[]=[],tasks:(()=>void)[]=[];const session=()=>signedIn?{access_token:token,user:{id}} as Session:null;const client={auth:{getSession:async()=>({error:null,data:{session:session()}}),getUser:async()=>({error:null,data:{user:{id,is_anonymous:false}}}),onAuthStateChange:(f:typeof listener)=>{listener=f;return{data:{subscription:{unsubscribe:()=>{}}}}},signUp:async(args:unknown)=>{calls.push({name:'signup',args});if(hold)await hold;if(autoSession){signedIn=true;listener?.('SIGNED_IN',session())}return{error:fail==='signup'?Error('Email exists'):null,data:{session:session(),user:{id}}}},resetPasswordForEmail:async(...args:unknown[])=>{calls.push({name:'recover',args});if(hold)await hold;return{error:fail==='recover'?Error('Not found'):null,data:{}}},updateUser:async(args:unknown)=>{calls.push({name:'update',args});if(hold)await hold;listener?.('USER_UPDATED',session());return{error:fail==='update'?Error('Policy refused'):null,data:{user:{id}}}},signOut:async(args:unknown)=>{calls.push({name:'logout',args});if(fail==='logout')return{error:Error('Denied')};signedIn=false;listener?.('SIGNED_OUT',null);return{error:null}}},from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({error:null,data:null})})})})} as unknown as SupabaseClient<Database>;const controller=createAccountSession(client,s=>states.push(s),task=>{tasks.push(task);return()=>{const i=tasks.indexOf(task);if(i>=0)tasks.splice(i,1)}},url);return{controller,calls,states,tasks,get last(){return states.at(-1)!},hold:(p:Promise<void>)=>hold=p,fail:(value:string)=>fail=value,auto:()=>autoSession=true,recovery:()=>{signedIn=true;listener?.('PASSWORD_RECOVERY',session())},event:(event:string)=>listener?.(event,session()),switch:()=>{id='u2';token='t2';listener?.('SIGNED_IN',session())},signedIn:()=>signedIn=true}}
async function start(m:ReturnType<typeof mock>){m.controller.start();for(let i=0;i<12;i++)await Promise.resolve()}
it('signup supplies email password and fixed callback only; does not forge profile role',async()=>{const m=mock();await start(m);await m.controller.signup(' user@example.invalid ',password);expect(m.calls).toEqual([{name:'signup',args:{email:'user@example.invalid',password,options:{emailRedirectTo:redirect}}}]);expect(m.last.phase).toBe('signed_out');expect(m.last.profile).toBeNull()})
it('signup with immediate session still requires own database profile',async()=>{const m=mock();await start(m);m.auto();await m.controller.signup('user@example.invalid',password);expect(m.last.phase).toBe('profile_missing');expect(m.last.profile).toBeNull()})
it('reset request sends email and fixed callback, does not update password',async()=>{const m=mock();await start(m);await m.controller.recover('user@example.invalid');expect(m.calls).toEqual([{name:'recover',args:['user@example.invalid',{redirectTo:redirect}]}]);expect(m.last.phase).toBe('signed_out')})
it('invalid email password or insecure callback never reaches Auth mutations',async()=>{const m=mock();await start(m);await expect(m.controller.signup('invalid',password)).rejects.toThrow();for(const value of ['short','X'.repeat(73),'🔐'.repeat(20)])await expect(m.controller.signup('user@example.invalid',value)).rejects.toThrow();for(const url of ['http://example.invalid/conta-supabase','https://example.invalid/conta-supabase?next=https://evil.invalid','https://user:pass@example.invalid/conta-supabase','https://example.invalid/other']){const x=mock(url);await start(x);await expect(x.controller.recover('user@example.invalid')).rejects.toThrow();expect(x.calls).toHaveLength(0)}expect(m.calls).toHaveLength(0)})
it('signup and recovery require signed-out SDK session',async()=>{const m=mock();await start(m);m.signedIn();await expect(m.controller.signup('user@example.invalid',password)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('mail cooldown rejects repeated attempts, synchronous lock rejects overlap',async()=>{const m=mock();await start(m);let done!:()=>void;m.hold(new Promise<void>(r=>done=r));const pending=m.controller.recover('user@example.invalid');await expect(m.controller.recover('user@example.invalid')).rejects.toThrow();done();await pending;await expect(m.controller.signup('user@example.invalid',password)).rejects.toThrow();expect(m.calls).toHaveLength(1)})
it('recovery event is synchronous and schedules no SDK profile calls; refresh preserves recovery form',async()=>{const m=mock();await start(m);m.recovery();expect(m.last.phase).toBe('password_recovery');expect(m.tasks).toHaveLength(0);expect(m.last.profile).toBeNull();await m.controller.refresh();expect(m.last.phase).toBe('password_recovery')})
it('normal session cannot change recovered password without recovery event',async()=>{const m=mock();await start(m);m.signedIn();await m.controller.refresh();await expect(m.controller.updateRecoveredPassword(password)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('valid recovery updates only password and exits device session before declaring completion',async()=>{const m=mock();await start(m);m.recovery();await m.controller.updateRecoveredPassword(password);expect(m.calls).toEqual([{name:'update',args:{password}},{name:'logout',args:{scope:'local'}}]);expect(m.last.phase).toBe('signed_out');expect(m.last.profile).toBeNull()})
it('failed password update keeps recovery form and never signs out as success',async()=>{const m=mock();await start(m);m.recovery();m.fail('update');await expect(m.controller.updateRecoveredPassword(password)).rejects.toThrow();expect(m.last.phase).toBe('password_recovery');expect(m.calls.map(c=>c.name)).toEqual(['update']);expect(m.last.error).not.toContain('Policy refused')})
it('changed account invalidates recovery binding before any update',async()=>{const m=mock();await start(m);m.recovery();m.switch();await expect(m.controller.updateRecoveredPassword(password)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('SDK account-existence errors are replaced with the same generic failure',async()=>{for(const operation of ['signup','recover'] as const){const m=mock();await start(m);m.fail(operation);await expect(operation==='signup'?m.controller.signup('user@example.invalid',password):m.controller.recover('user@example.invalid')).rejects.toThrow('Não foi possível concluir a operação.');expect(m.last.error).not.toContain('exists');expect(m.last.error).not.toContain('found')}})
it('failed logout does not announce recovered flow completed',async()=>{const m=mock();await start(m);m.recovery();m.fail('logout');await expect(m.controller.updateRecoveredPassword(password)).rejects.toThrow();expect(m.last.phase).toBe('error');expect(m.last.profile).toBeNull()})
