import {it,expect} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {createAccountSession,type AccountState} from './accountSession'
import fs from 'node:fs'
function mock(){let signedIn=false,token='t1',row:{id:string;display_name:string;role:string;approved:boolean;created_at:string}|null={id:'u1',display_name:'Name',role:'aluno',approved:false,created_at:'now'},listener:((e:string,s:unknown)=>void)|undefined,hold:Promise<void>|null=null,failLogout=false;const calls:string[]=[],states:AccountState[]=[],tasks:(()=>void)[]=[];const client={auth:{getSession:async()=>({error:null,data:{session:signedIn?{access_token:token,user:{id:'u1'}}:null}}),getUser:async()=>({error:null,data:{user:{id:'u1',is_anonymous:false,user_metadata:{role:'admin'}}}}),onAuthStateChange:(f:(e:string,s:unknown)=>void)=>{listener=f;return{data:{subscription:{unsubscribe:()=>calls.push('unsubscribe')}}}},signInWithPassword:async()=>{calls.push('login');if(hold)await hold;signedIn=true;listener?.('SIGNED_IN',{});return{error:null,data:{session:{user:{id:'u1'}}}}},signOut:async()=>{calls.push('logout');if(failLogout)return{error:Error('Denied')};signedIn=false;listener?.('SIGNED_OUT',null);return{error:null}}},from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>{calls.push('profile');if(hold)await hold;return{error:null,data:row}}})})})} as unknown as SupabaseClient<Database>;const controller=createAccountSession(client,s=>states.push(s),task=>{tasks.push(task);return()=>{const i=tasks.indexOf(task);if(i>=0)tasks.splice(i,1)}});return{controller,calls,states,tasks,get last(){return states.at(-1)!},signedIn:()=>signedIn=true,setRow:(r:typeof row)=>row=r,hold:(p:Promise<void>|null)=>hold=p,failLogout:()=>failLogout=true,event:(e:string,s:unknown)=>listener?.(e,s)}}
async function settle(){for(let i=0;i<12;i++)await Promise.resolve()}
it('restores signed-out state without profile read',async()=>{const m=mock();m.controller.start();await settle();expect(m.last.phase).toBe('signed_out');expect(m.calls).not.toContain('profile')})
it('login loads database role rather than editable metadata',async()=>{const m=mock();m.controller.start();await settle();await m.controller.login('user@example.invalid','password');expect(m.last.phase).toBe('ready');expect(m.last.profile?.role).toBe('aluno')})
it('no profile gives creation state without inventing a user role',async()=>{const m=mock();m.signedIn();m.setRow(null);m.controller.start();await settle();expect(m.last.phase).toBe('profile_missing');expect(m.last.profile).toBeNull()})
it('auth callback schedules SDK access without calling it inside callback',async()=>{const m=mock();m.controller.start();await settle();m.signedIn();m.event('TOKEN_REFRESHED',{});expect(m.calls).not.toContain('profile');expect(m.last.profile).toBeNull();expect(m.tasks.length).toBe(1);m.tasks.shift()!();await settle();expect(m.last.phase).toBe('ready')})
it('logout clears owned data and refuses optimistic success if signOut fails',async()=>{const m=mock();m.signedIn();m.controller.start();await settle();m.failLogout();await expect(m.controller.logout()).rejects.toThrow();expect(m.last.phase).toBe('error');expect(m.last.profile).toBeNull();expect(m.last.busy).toBe(false)})
it('successful logout ends signed out and local profile is cleared',async()=>{const m=mock();m.signedIn();m.controller.start();await settle();await m.controller.logout();expect(m.last.phase).toBe('signed_out');expect(m.last.profile).toBeNull()})
it('synchronous operation lock rejects repeated login and concurrent logout',async()=>{const m=mock();m.controller.start();await settle();let done!:()=>void;m.hold(new Promise<void>(r=>done=r));const first=m.controller.login('user@example.invalid','password');await expect(m.controller.login('user@example.invalid','password')).rejects.toThrow('Aguarde');await expect(m.controller.logout()).rejects.toThrow('Aguarde');m.hold(null);done();await first;expect(m.calls.filter(x=>x==='login').length).toBe(1)})
it('dispose prevents pending profile results from updating UI and unsubscribes',async()=>{const m=mock();m.signedIn();let done!:()=>void;m.hold(new Promise<void>(r=>done=r));m.controller.start();await settle();m.controller.dispose();const n=m.states.length;m.hold(null);done();await settle();expect(m.states.length).toBe(n);expect(m.calls).toContain('unsubscribe')})
it('sign-out event invalidates old profile response',async()=>{const m=mock();m.signedIn();let done!:()=>void;m.hold(new Promise<void>(r=>done=r));m.controller.start();await settle();m.event('SIGNED_OUT',null);m.hold(null);done();await settle();expect(m.last.phase).toBe('signed_out');expect(m.last.profile).toBeNull()})
it('malformed input causes no login request and unknown database role is blocked',async()=>{const m=mock();await expect(m.controller.login('','')).rejects.toThrow();expect(m.calls).not.toContain('login');m.signedIn();m.setRow({id:'u1',display_name:'X',role:'root',approved:true,created_at:'now'});m.controller.start();await settle();expect(m.last.phase).toBe('error');expect(m.last.profile).toBeNull()})
it('account route is separated from legacy provider and embedded quick login is removed',()=>{const app=fs.readFileSync('src/App.tsx','utf8'),page=fs.readFileSync('src/pages/SupabaseAccount.tsx','utf8'),login=fs.readFileSync('src/pages/Login.tsx','utf8');expect(app).toContain('path="/conta-supabase"');expect(app.slice(app.indexOf('export default function App'))).not.toContain('<AuthProvider>');expect(page).not.toContain('pocketbase');expect(page).not.toContain('useAuth');expect(login).not.toContain('handleQuickLogin');expect(login).not.toContain('targetPass')})
