import {it,expect} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {createAccountSession,type AccountState} from './accountSession'
import type {StudentLink} from './links'
const student='11111111-1111-4111-8111-111111111111',professional='22222222-2222-4222-8222-222222222222'
const link:StudentLink={student_id:student,professional_id:professional,state:'pending',version:3,requested_at:'2026-10-05T00:00:00Z',accepted_at:null,revoked_at:null}
function mock(role='profissional',approved=true){const id=role==='aluno'?student:professional;let hold:Promise<void>|null=null,fail=false;const calls:{name:string;args:unknown}[]=[],states:AccountState[]=[];const client={auth:{getSession:async()=>({error:null,data:{session:{access_token:'token',user:{id}}}}),getUser:async()=>({error:null,data:{user:{id,is_anonymous:false}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe:()=>{}}}})},from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({error:null,data:{id,role,approved,display_name:'Nome',created_at:'now'}})})})}),rpc:(name:string,args:{p_student_id:string;p_expected_version:number;p_professional_id?:string})=>({single:async()=>{calls.push({name,args});if(hold)await hold;return{error:fail?Error('Denied'):null,data:fail?null:{...link,student_id:args.p_student_id||id,professional_id:args.p_professional_id||professional,version:args.p_expected_version||1,state:name==='accept_student_link'?'active':name==='request_student_link'?'pending':'revoked'}}}})} as unknown as SupabaseClient<Database>;const controller=createAccountSession(client,s=>states.push(s));return{controller,calls,states,get last(){return states.at(-1)!},hold:(p:Promise<void>)=>hold=p,fail:()=>fail=true}}
async function ready(m:ReturnType<typeof mock>){m.controller.start();for(let i=0;i<12;i++)await Promise.resolve();expect(m.last.phase).toBe('ready')}
it('approved chosen professional accepts exact displayed version then reloads account',async()=>{const m=mock();await ready(m);await m.controller.acceptLink({...link});expect(m.calls).toEqual([{name:'accept_student_link',args:{p_student_id:student,p_expected_version:3}}]);expect(m.last.phase).toBe('ready');expect(m.last.busy).toBe(false)})
it('student, unapproved professional and administrator cannot accept',async()=>{for(const [role,approved] of [['aluno',true],['profissional',false],['admin',true]] as const){const m=mock(role,approved);await ready(m);expect(()=>m.controller.acceptLink({...link})).toThrow();expect(m.calls).toHaveLength(0)}})
it('foreign participant, revoked and already accepted rows cannot be accepted',async()=>{const m=mock();await ready(m);for(const row of [{...link,professional_id:student},{...link,state:'revoked'},{...link,state:'active'}] as StudentLink[])expect(()=>m.controller.acceptLink(row)).toThrow();expect(m.calls).toHaveLength(0)})
it('student can revoke own pending link; approved professional can revoke active link',async()=>{for(const role of ['aluno','profissional']){const m=mock(role);await ready(m);await m.controller.revokeLink({...link,state:role==='aluno'?'pending':'active'});expect(m.calls[0]).toEqual({name:'revoke_student_link',args:{p_student_id:student,p_expected_version:3}})}})
it('cannot revoke foreign or revoked row, or mutate before restored session',async()=>{const m=mock('aluno');expect(()=>m.controller.revokeLink({...link})).toThrow();await ready(m);expect(()=>m.controller.revokeLink({...link,student_id:professional})).toThrow();expect(()=>m.controller.revokeLink({...link,state:'revoked'})).toThrow();expect(m.calls).toHaveLength(0)})
it('pending RPC blocks duplicate submission and account edits; target snapshot is immutable',async()=>{const m=mock();await ready(m);let done!:()=>void;m.hold(new Promise<void>(r=>done=r));const row={...link},pending=m.controller.acceptLink(row);row.student_id=professional;row.version=99;expect(()=>m.controller.acceptLink({...link})).toThrow();await expect(m.controller.renameProfile('Outro')).rejects.toThrow();done();await pending;expect(m.calls).toHaveLength(1);expect(m.calls[0].args).toEqual({p_student_id:student,p_expected_version:3})})
it('server refusal clears owned state and is not reported as success',async()=>{const m=mock();await ready(m);m.fail();await expect(m.controller.acceptLink({...link})).rejects.toThrow();expect(m.last.phase).toBe('error');expect(m.last.profile).toBeNull();expect(m.last.busy).toBe(false)})
it('unmount ignores pending mutation result',async()=>{const m=mock();await ready(m);let done!:()=>void;m.hold(new Promise<void>(r=>done=r));const pending=m.controller.revokeLink({...link});m.controller.dispose();const n=m.states.length;done();await pending;expect(m.states).toHaveLength(n)})

it('restored student requests chosen professional without client actor/role/state',async()=>{const m=mock('aluno');await ready(m);await m.controller.requestLink(professional);expect(m.calls).toEqual([{name:'request_student_link',args:{p_professional_id:professional}}]);expect(m.last.phase).toBe('ready')})
it('request before restoration, from professional/admin, or after disposal is blocked',async()=>{const m=mock('aluno');expect(()=>m.controller.requestLink(professional)).toThrow();await ready(m);m.controller.dispose();expect(()=>m.controller.requestLink(professional)).toThrow();expect(m.calls).toHaveLength(0);for(const role of ['profissional','admin']){const x=mock(role);await ready(x);expect(()=>x.controller.requestLink(professional)).toThrow();expect(x.calls).toHaveLength(0)}})
it('pending request blocks repeat request and accepts no mutation from another action',async()=>{const m=mock('aluno');await ready(m);let done!:()=>void;m.hold(new Promise<void>(r=>done=r));const pending=m.controller.requestLink(professional);expect(()=>m.controller.requestLink(professional)).toThrow();expect(()=>m.controller.revokeLink({...link})).toThrow();done();await pending;expect(m.calls).toHaveLength(1)})
