import {expect,it} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {readAdminParticipantOverview as read,type ParticipantOverview} from './adminOverview'
const admin='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222'
const row:ParticipantOverview={participant_id:other,display_name:'Participant',participant_role:'aluno',professional_approved:false,joined_at:'2026-10-08T00:00:00Z',wallet_initialized:false,available_cents:null,reserved_cents:null,wallet_version:null,wallet_updated_at:null,esg_pending:1,esg_approved:0,esg_rejected:0,checked_at:'2026-10-08T17:00:00Z'}
function mock(){
 const state={id:admin,role:'admin',anonymous:false,token:'t1',fail:false,rows:[{...row}] as ParticipantOverview[],onResult:()=>{}}
 const calls:unknown[]=[]
 const client={auth:{getSession:async()=>({error:null,data:{session:{access_token:state.token,user:{id:state.id}}}}),getUser:async()=>({error:null,data:{user:{id:state.id,is_anonymous:state.anonymous,user_metadata:{role:'admin'}}}})},from:()=>({select(){return this},eq(){return this},async maybeSingle(){return {error:null,data:{id:state.id,role:state.role,display_name:'Admin',approved:false,created_at:'2026-10-08T00:00:00Z'}}}}),rpc:async(name:string,args:unknown)=>{calls.push({name,args});state.onResult();return{error:state.fail?Error('denied'):null,data:state.rows}}} as unknown as SupabaseClient<Database>
 return {state,calls,client}
}
it('queries only the administrative RPC with bounded page and normalized search',async()=>{const m=mock();const result=await read(admin,2,' Name ',m.client);expect(m.calls).toEqual([{name:'admin_participant_overview',args:{p_page:2,p_query:'Name'}}]);expect(result).toEqual([row]);expect(result[0]).not.toBe(m.state.rows[0])})
it('rejects participants forged metadata anonymous auth and a changed owner before querying',async()=>{const m=mock();for(const role of ['aluno','profissional']){m.state.role=role;await expect(read(admin,1,'',m.client)).rejects.toThrow()}m.state.role='admin';m.state.anonymous=true;await expect(read(admin,1,'',m.client)).rejects.toThrow();m.state.anonymous=false;m.state.id=other;await expect(read(admin,1,'',m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('invalid pages oversized search and malformed expected account make no RPC',async()=>{const m=mock();for(const page of [0,-1,1.5,10001,NaN])await expect(read(admin,page,'',m.client)).rejects.toThrow();await expect(read(admin,1,'a'.repeat(121),m.client)).rejects.toThrow();await expect(read('bad',1,'',m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('missing wallet remains null and a real zero wallet is distinguishable',async()=>{const m=mock();expect((await read(admin,1,'',m.client))[0].available_cents).toBeNull();m.state.rows=[{...row,wallet_initialized:true,available_cents:0,reserved_cents:0,wallet_version:1,wallet_updated_at:row.checked_at}];expect((await read(admin,1,'',m.client))[0]).toMatchObject({wallet_initialized:true,available_cents:0})})
it('rejects malformed summaries inconsistent money and incomplete balances',async()=>{const m=mock();for(const patch of [{available_cents:0},{esg_pending:-1},{esg_approved:1.1},{participant_role:'admin'},{checked_at:'bad'},{wallet_initialized:true},{wallet_initialized:true,available_cents:Number.MAX_SAFE_INTEGER,reserved_cents:1,wallet_version:1,wallet_updated_at:row.checked_at}]){m.state.rows=[{...row,...patch}];await expect(read(admin,1,'',m.client)).rejects.toThrow()}})
it('duplicate oversized and failed responses are rejected with no partial success',async()=>{const m=mock();m.state.rows=[row,row];await expect(read(admin,1,'',m.client)).rejects.toThrow();m.state.rows=Array(21).fill(row);await expect(read(admin,1,'',m.client)).rejects.toThrow();m.state.rows=[];m.state.fail=true;await expect(read(admin,1,'',m.client)).rejects.toThrow()})
it('session changes discard returned data and unknown response fields are not exposed',async()=>{const m=mock();m.state.rows=[{...row,secret:'should not propagate'} as ParticipantOverview];expect(await read(admin,1,'',m.client)).toEqual([row]);m.state.onResult=()=>{m.state.token='t2'};await expect(read(admin,1,'',m.client)).rejects.toThrow('Sessão alterada')})
