import {it,expect} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {submitApplication,reviewApplication,readOwnApplication,readApplicationQueue,type Application} from './applications'
import {createAccountSession,type AccountState} from './accountSession'
const student='11111111-1111-4111-8111-111111111111',admin='22222222-2222-4222-8222-222222222222',other='33333333-3333-4333-8333-333333333333'
const application:Application={applicant_id:student,applicant_name:'Applicant',specialty:'educacao_fisica',credential:'Registration',status:'pending',version:2,requested_at:'2026-10-06T12:00:00Z',reviewed_at:null,review_reason:null}
function mock(role='aluno'){
 const state={id:role==='admin'?admin:student,token:'t1',fail:false,row:{...application} as Application,override:false,onResult:()=>{},hold:null as Promise<void>|null}
 const calls:unknown[][]=[],states:AccountState[]=[]
 const client={auth:{getSession:async()=>({error:null,data:{session:{access_token:state.token,user:{id:state.id}}}}),getUser:async()=>({error:null,data:{user:{id:state.id,is_anonymous:false,user_metadata:{role:'admin'}}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe:()=>{}}}})},from:(table:string)=>{calls.push(['from',table]);return{select(...args:unknown[]){calls.push(['select',...args]);return this},eq(...args:unknown[]){calls.push(['eq',...args]);return this},order(...args:unknown[]){calls.push(['order',...args]);return this},async range(...args:unknown[]){calls.push(['range',...args]);state.onResult();return{error:state.fail?Error('Denied'):null,data:[state.row]}},async maybeSingle(){state.onResult();return{error:state.fail?Error('Denied'):null,data:table==='profiles'?{id:state.id,display_name:'Name',role,approved:false,created_at:'now'}:state.row}}}},rpc:(name:string,args:Record<string,unknown>)=>({single:async()=>{calls.push(['rpc',name,args]);if(state.hold)await state.hold;state.onResult();const data=state.override?state.row:name==='submit_professional_application'?{...state.row,applicant_id:state.id,specialty:args.p_specialty,credential:args.p_credential,status:'pending',review_reason:null,reviewed_at:null}:{...state.row,applicant_id:args.p_applicant_id,version:args.p_expected_version,status:args.p_decision,review_reason:args.p_reason,reviewed_at:'2026-10-06T13:00:00Z'};return{error:state.fail?Error('Denied'):null,data}}})} as unknown as SupabaseClient<Database>
 const controller=createAccountSession(client,s=>states.push(s));return{state,calls,client,controller,states,get last(){return states.at(-1)!}}
}
async function ready(m:ReturnType<typeof mock>){m.controller.start();for(let i=0;i<12;i++)await Promise.resolve();expect(m.last.phase).toBe('ready');m.calls.length=0}
it('submission sends specialty and credential only, with verified owner',async()=>{const m=mock();const row=await submitApplication('nutricao',' Credential ',student,m.client);expect(m.calls).toEqual([['rpc','submit_professional_application',{p_specialty:'nutricao',p_credential:'Credential'}]]);expect(row.applicant_id).toBe(student);expect(row.status).toBe('pending')})
it('invalid input and switched owner make no mutation',async()=>{const m=mock();await expect(submitApplication('admin' as never,'X',student,m.client)).rejects.toThrow();await expect(submitApplication('nutricao',' ',student,m.client)).rejects.toThrow();await expect(submitApplication('nutricao','X'.repeat(161),student,m.client)).rejects.toThrow();m.state.id=other;await expect(submitApplication('nutricao','X',student,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('review binds applicant exact version and reason, without actor role or approval field',async()=>{const m=mock('admin');await reviewApplication(application,'approved',' Verified ',admin,m.client);expect(m.calls).toEqual([['rpc','review_professional_application',{p_applicant_id:student,p_expected_version:2,p_decision:'approved',p_reason:'Verified'}]])})
it('self review invalid decision or stale/finished local state blocked',async()=>{const m=mock('admin');for(const row of [{...application,applicant_id:admin},{...application,version:0},{...application,status:'approved'}])await expect(reviewApplication(row,'approved','Checked',admin,m.client)).rejects.toThrow();await expect(reviewApplication(application,'pending' as never,'Checked',admin,m.client)).rejects.toThrow();await expect(reviewApplication(application,'approved',' ',admin,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('mismatched returned applicant/version/status or session change rejected',async()=>{const m=mock('admin');m.state.override=true;for(const changes of [{applicant_id:other,status:'approved',reviewed_at:'2026-10-06T13:00:00Z',review_reason:'Checked'},{version:99,status:'approved'},{status:'pending'}]){m.state.row={...application,...changes};await expect(reviewApplication(application,'approved','Checked',admin,m.client)).rejects.toThrow()}const s=mock();s.state.onResult=()=>{s.state.token='t2'};await expect(submitApplication('nutricao','X',student,s.client)).rejects.toThrow('Sessão alterada')})
it('own read binds owner; queue reads pending twenty per page in stable order',async()=>{const own=mock();await readOwnApplication(student,own.client);expect(own.calls).toContainEqual(['eq','applicant_id',student]);const m=mock('admin');await readApplicationQueue(admin,2,m.client);expect(m.calls).toContainEqual(['eq','status','pending']);expect(m.calls).toContainEqual(['range',20,39]);expect(m.calls).toContainEqual(['order','requested_at']);expect(m.calls).toContainEqual(['order','applicant_id'])})
it('foreign own-row and nonpending queue-row are not displayed',async()=>{const m=mock();m.state.row={...application,applicant_id:other};await expect(readOwnApplication(student,m.client)).rejects.toThrow();const a=mock('admin');a.state.row={...application,status:'approved'};await expect(readApplicationQueue(admin,1,a.client)).rejects.toThrow()})
it('server refuses mutation without optimistic success',async()=>{const m=mock('admin');m.state.fail=true;await expect(reviewApplication(application,'approved','Checked',admin,m.client)).rejects.toThrow();const s=mock();s.state.fail=true;await expect(submitApplication('nutricao','X',student,s.client)).rejects.toThrow()})
it('controller lets student submit but cannot review based on editable metadata',async()=>{const m=mock();await ready(m);await m.controller.applyProfessional('nutricao','Credential');expect(m.calls).toContainEqual(['rpc','submit_professional_application',{p_specialty:'nutricao',p_credential:'Credential'}]);expect(m.last.profile?.role).toBe('aluno');expect(()=>m.controller.reviewProfessional(application,'approved','Checked')).toThrow()})
it('controller only database administrator can review',async()=>{for(const role of ['aluno','profissional']){const m=mock(role);await ready(m);expect(()=>m.controller.reviewProfessional(application,'approved','Checked')).toThrow();expect(m.calls).toHaveLength(0)}const a=mock('admin');await ready(a);expect(()=>a.controller.applyProfessional('nutricao','Credential')).toThrow();await a.controller.reviewProfessional(application,'rejected','Evidence incomplete');expect(a.last.profile?.role).toBe('admin')})
it('controller snapshot and synchronous lock prevent changed target and duplicate review',async()=>{const m=mock('admin');await ready(m);let done!:()=>void;m.state.hold=new Promise<void>(r=>done=r);const row={...application},pending=m.controller.reviewProfessional(row,'approved','Checked');row.applicant_id=other;row.version=99;expect(()=>m.controller.reviewProfessional(application,'approved','Checked')).toThrow();await expect(m.controller.renameProfile('New')).rejects.toThrow();done();await pending;expect(m.calls.filter(x=>x[0]==='rpc')).toEqual([['rpc','review_professional_application',{p_applicant_id:student,p_expected_version:2,p_decision:'approved',p_reason:'Checked'}]])})
it('controller database failure clears owned data and does not announce approval',async()=>{const m=mock('admin');await ready(m);m.state.fail=true;await expect(m.controller.reviewProfessional(application,'approved','Checked')).rejects.toThrow();expect(m.last.phase).toBe('error');expect(m.last.profile).toBeNull()})
