import {it,expect} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {calendarDay,monthDays,shiftMonth,saoPauloToday,saoPauloHour,lastAvailabilityDay,validateAvailability,saveOwnAvailability,readOwnAvailability,readReleasedAvailability,type AvailabilityInput} from './availability'
import {createAccountSession,type AccountState} from './accountSession'
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',day='2026-10-08',stamp='2026-10-07T12:00:00Z',month='2026-10-01'
const input:AvailabilityInput={day,expectedVersion:0,hours:[5,23],released:false}
function mock(){const state={id:owner,token:'one',role:'profissional',approved:true,fail:false,onResult:()=>{},override:{} as Record<string,unknown>,rows:null as unknown[]|null},calls:unknown[][]=[],states:AccountState[]=[];const base={professional_id:owner,day,available_hours:[5,23],released:false,version:1,updated_at:stamp}
 const client={auth:{getSession:async()=>({error:null,data:{session:{access_token:state.token,user:{id:state.id}}}}),getUser:async()=>({error:null,data:{user:{id:state.id,is_anonymous:false}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe:()=>{}}}})},rpc:(name:string,args:Record<string,unknown>)=>{calls.push(['rpc',name,{...args}]);const response=()=>{state.onResult();return{error:state.fail?Error('Denied'):null,data:name==='save_professional_availability'?{...base,day:args.p_day,available_hours:args.p_hours,version:Number(args.p_expected_version)+1,released:args.p_released,...state.override}:state.rows??[{professional_id:other,day,available_hours:[5,23],...state.override}]}};return{single:async()=>response(),then:(done:(r:unknown)=>unknown)=>Promise.resolve(response()).then(done)}},from:(table:string)=>{calls.push(['from',table]);return{select(){return this},eq(key:string,value:string){calls.push(['eq',key,value]);return this},gte(key:string,value:string){calls.push(['gte',key,value]);return this},lte(key:string,value:string){calls.push(['lte',key,value]);return this},order(){return this},async limit(n:number){calls.push(['limit',n]);state.onResult();return{error:null,data:state.rows??[{...base,...state.override}]}},async maybeSingle(){return{error:null,data:{id:state.id,display_name:'Name',role:state.role,approved:state.approved,created_at:stamp}}}}}} as unknown as SupabaseClient<Database>;const controller=createAccountSession(client,s=>states.push(s));return{state,calls,client,controller,base,get last(){return states.at(-1)!}}}
async function ready(m:ReturnType<typeof mock>){m.controller.start();for(let n=0;n<12;n++)await Promise.resolve();expect(m.last.phase).toBe('ready');m.calls.length=0}
it('valid calendar dates reject rollover and month requires first day',()=>{expect(monthDays('2028-02-01')).toHaveLength(29);expect(monthDays('2026-02-01')).toHaveLength(28);for(const value of ['2026-02-29','2026-13-01','2026-1-1','bad'])expect(()=>calendarDay(value)).toThrow();expect(()=>monthDays('2026-10-02')).toThrow()})
it('month navigation handles December January and preserves leap boundaries',()=>{expect(shiftMonth('2026-12-01',1)).toBe('2027-01-01');expect(shiftMonth('2027-01-01',-1)).toBe('2026-12-01');expect(lastAvailabilityDay('2027-03-01')).toBe('2028-03-01')})
it('calendar uses Sao Paulo date and hour across UTC midnight',()=>{const now=new Date('2026-10-08T01:30:00Z');expect(saoPauloToday(now)).toBe('2026-10-07');expect(saoPauloHour(now)).toBe(22)})
it('availability validates canonical hours empty unreleased and version bounds',()=>{expect(validateAvailability({...input,hours:[23,5]}).hours).toEqual([5,23]);expect(validateAvailability({...input,hours:[]}).hours).toEqual([]);for(const patch of [{hours:[5,5]},{hours:[4]},{hours:[24]},{hours:[5.5]},{hours:[NaN]},{hours:Array(1)},{hours:[],released:true},{expectedVersion:-1},{expectedVersion:1.2},{expectedVersion:Number.MAX_SAFE_INTEGER}])expect(()=>validateAvailability({...input,...patch})).toThrow()})
it('save sends day version hours and release with implicit owner',async()=>{const m=mock();await saveOwnAvailability(input,owner,m.client);expect(m.calls.filter(c=>c[0]==='rpc')).toEqual([['rpc','save_professional_availability',{p_day:day,p_expected_version:0,p_hours:[5,23],p_released:false}]])})
it('foreign signed-in actor and unapproved professional cannot save',async()=>{const m=mock();await expect(saveOwnAvailability(input,other,m.client)).rejects.toThrow();m.state.approved=false;await expect(saveOwnAvailability(input,owner,m.client)).rejects.toThrow();expect(m.calls.filter(c=>c[0]==='rpc')).toHaveLength(0)})
it('save refuses unexpected version owner or hours instead of optimistic success',async()=>{for(const override of [{version:4},{professional_id:other},{available_hours:[5]},{released:true},{day:'2026-10-09'}]){const m=mock();m.state.override=override;await expect(saveOwnAvailability(input,owner,m.client)).rejects.toThrow()}})
it('token change after response clears confirmation',async()=>{const m=mock();m.state.onResult=()=>{m.state.token='two'};await expect(saveOwnAvailability(input,owner,m.client)).rejects.toThrow('Sessão alterada')})
it('professional reads only own bounded month range',async()=>{const m=mock();await readOwnAvailability(owner,month,m.client);expect(m.calls).toContainEqual(['eq','professional_id',owner]);expect(m.calls).toContainEqual(['gte','day','2026-10-01']);expect(m.calls).toContainEqual(['lte','day','2026-10-31']);expect(m.calls).toContainEqual(['limit',32])})
it('corrupt duplicate foreign or out-of-month day snapshots fail closed',async()=>{for(const override of [{professional_id:other},{day:'2026-11-01'},{available_hours:[23,5]},{version:0},{updated_at:'bad'}]){const m=mock();m.state.override=override;await expect(readOwnAvailability(owner,month,m.client)).rejects.toThrow()}const m=mock();m.state.rows=[m.base,m.base];await expect(readOwnAvailability(owner,month,m.client)).rejects.toThrow()})
it('student requests released minimal rows for one selected professional',async()=>{const m=mock();m.state.role='aluno';const rows=await readReleasedAvailability(other,month,owner,m.client);expect(rows).toEqual([{professional_id:other,day,available_hours:[5,23]}]);expect(m.calls).toContainEqual(['rpc','list_released_availability',{p_professional_id:other,p_month:month}])})
it('student rejects foreign provider duplicate or empty released rows',async()=>{for(const override of [{professional_id:owner},{available_hours:[]},{day:'2026-11-01'}]){const m=mock();m.state.role='aluno';m.state.override=override;await expect(readReleasedAvailability(other,month,owner,m.client)).rejects.toThrow()}const m=mock();m.state.role='aluno';m.state.rows=[{professional_id:other,day,available_hours:[5]},{professional_id:other,day,available_hours:[5]}];await expect(readReleasedAvailability(other,month,owner,m.client)).rejects.toThrow()})
it('controller shares busy lock and copies hours before await',async()=>{const m=mock();await ready(m);const body={...input,hours:[5,23]};const pending=m.controller.saveAvailability(body);body.hours.push(12);expect(()=>m.controller.saveAvailability(input)).toThrow();await pending;expect(m.calls.find(c=>c[0]==='rpc')![2]).toMatchObject({p_hours:[5,23]})})
it('controller blocks unready admin and student availability mutation',async()=>{const m=mock();expect(()=>m.controller.saveAvailability(input)).toThrow();for(const role of ['admin','aluno']){m.state.role=role;await m.controller.refresh();expect(()=>m.controller.saveAvailability(input)).toThrow()}expect(m.calls.filter(c=>c[0]==='rpc')).toHaveLength(0)})
it('server conflict causes cleared profile and no automatic overwrite retry',async()=>{const m=mock();await ready(m);m.state.fail=true;await expect(m.controller.saveAvailability({...input,expectedVersion:3})).rejects.toThrow();expect(m.last.profile).toBeNull();expect(m.calls.filter(c=>c[0]==='rpc')).toHaveLength(1)})
