import {it,expect} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {depositCents,parseDepositPercentage,validateBookingTerms,saveBookingTerms,readOwnBookingTerms,readProfessionalBookingTerms,type BookingTermsInput} from './bookingTerms'
import {createAccountSession,type AccountState} from './accountSession'
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',key='33333333-3333-4333-8333-333333333333',id='44444444-4444-4444-8444-444444444444',stamp='2026-10-07T17:00:00Z'
const input:BookingTermsInput={expectedVersion:0,priceCents:20000,depositBasisPoints:2500,freeCancelHours:48}
function mock(){const state={id:owner,token:'one',role:'profissional',approved:true,fail:false,missing:false,onResult:()=>{},override:{} as Record<string,unknown>},calls:unknown[][]=[],states:AccountState[]=[];const base={id,professional_id:owner,request_id:key,version:1,price_cents:20000,deposit_basis_points:2500,deposit_cents:5000,free_cancel_hours:48,no_show_deposit_retained:true,created_at:stamp}
 const client={auth:{getSession:async()=>({error:null,data:{session:{access_token:state.token,user:{id:state.id}}}}),getUser:async()=>({error:null,data:{user:{id:state.id,is_anonymous:false}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe:()=>{}}}})},rpc:(name:string,args:Record<string,unknown>)=>{const response=async()=>{calls.push(['rpc',name,{...args}]);state.onResult();return{error:state.fail?Error('Denied'):null,data:state.missing?null:name==='save_professional_booking_terms'?{...base,request_id:args.p_request_id,version:Number(args.p_expected_version)+1,price_cents:args.p_price_cents,deposit_basis_points:args.p_deposit_basis_points,deposit_cents:depositCents(Number(args.p_price_cents),Number(args.p_deposit_basis_points)),free_cancel_hours:args.p_free_cancel_hours,...state.override}:{...base,professional_id:args.p_professional_id,...state.override}}};return{single:response,maybeSingle:response}},from:(table:string)=>{calls.push(['from',table]);return{select(){return this},eq(field:string,value:string){calls.push(['eq',field,value]);return this},order(field:string,options:unknown){calls.push(['order',field,options]);return this},limit(n:number){calls.push(['limit',n]);return this},async maybeSingle(){if(table==='profiles')return{error:null,data:{id:state.id,display_name:'Name',role:state.role,approved:state.approved,created_at:stamp}};state.onResult();return{error:state.fail?Error('Denied'):null,data:state.missing?null:{...base,...state.override}}}}}} as unknown as SupabaseClient<Database>;const controller=createAccountSession(client,s=>states.push(s));return{state,calls,client,controller,get last(){return states.at(-1)!}}}
async function ready(m:ReturnType<typeof mock>){m.controller.start();for(let n=0;n<12;n++)await Promise.resolve();expect(m.last.phase).toBe('ready');m.calls.length=0}
it('deposit is exact, half-up and safe at maximum integer price',()=>{expect(depositCents(20000,2500)).toBe(5000);expect(depositCents(101,5000)).toBe(51);expect(depositCents(Number.MAX_SAFE_INTEGER,10000)).toBe(Number.MAX_SAFE_INTEGER);for(const pair of [[1,1],[0,2500],[100,0],[100,10001],[100.5,2500],[NaN,2500],[Number.MAX_SAFE_INTEGER+1,2500]])expect(()=>depositCents(...pair as [number,number])).toThrow()})
it('percentage parses comma dot and two decimals without implicit defaults',()=>{expect(parseDepositPercentage('25')).toBe(2500);expect(parseDepositPercentage('0,01')).toBe(1);expect(parseDepositPercentage('100.00')).toBe(10000);for(const value of ['','0','100.01','1e2','25.001','-1'])expect(()=>parseDepositPercentage(value)).toThrow()})
it('input validates versions and cancellation bounds',()=>{expect(validateBookingTerms({...input,freeCancelHours:0})).toMatchObject({freeCancelHours:0});for(const patch of [{expectedVersion:-1},{expectedVersion:Number.MAX_SAFE_INTEGER},{freeCancelHours:-1},{freeCancelHours:721},{freeCancelHours:1.5}])expect(()=>validateBookingTerms({...input,...patch})).toThrow()})
it('save sends only request version and financial terms with server-derived owner',async()=>{const m=mock();await saveBookingTerms(input,key,owner,m.client);expect(m.calls.filter(c=>c[0]==='rpc')).toEqual([['rpc','save_professional_booking_terms',{p_request_id:key,p_expected_version:0,p_price_cents:20000,p_deposit_basis_points:2500,p_free_cancel_hours:48}]])})
it('different actor, student or unapproved pro cannot issue save RPC',async()=>{const m=mock();await expect(saveBookingTerms(input,key,other,m.client)).rejects.toThrow();m.state.role='aluno';await expect(saveBookingTerms(input,key,owner,m.client)).rejects.toThrow();m.state.role='profissional';m.state.approved=false;await expect(saveBookingTerms(input,key,owner,m.client)).rejects.toThrow();expect(m.calls.filter(c=>c[0]==='rpc')).toHaveLength(0)})
it('rejects altered session after save and malformed financial responses',async()=>{const m=mock();m.state.onResult=()=>{m.state.token='two'};await expect(saveBookingTerms(input,key,owner,m.client)).rejects.toThrow('Sessão alterada');for(const override of [{deposit_cents:5001},{professional_id:other},{request_id:other},{version:3},{price_cents:30000},{no_show_deposit_retained:false},{created_at:'bad'}]){const x=mock();x.state.override=override;await expect(saveBookingTerms(input,key,owner,x.client)).rejects.toThrow()}})
it('professional reads only latest own terms and does not fabricate missing quote',async()=>{const m=mock();await readOwnBookingTerms(owner,m.client);expect(m.calls).toContainEqual(['eq','professional_id',owner]);expect(m.calls).toContainEqual(['order','version',{ascending:false}]);expect(m.calls).toContainEqual(['limit',1]);m.state.missing=true;expect(await readOwnBookingTerms(owner,m.client)).toBeNull()})
it('student fetches minimal quote for selected professional and validates owner',async()=>{const m=mock();m.state.role='aluno';expect((await readProfessionalBookingTerms(other,owner,m.client))?.professional_id).toBe(other);expect(m.calls).toContainEqual(['rpc','get_professional_booking_terms',{p_professional_id:other}]);m.state.override={professional_id:owner};await expect(readProfessionalBookingTerms(other,owner,m.client)).rejects.toThrow()})
it('student missing terms remains null and server errors are not interpreted as absent',async()=>{const m=mock();m.state.role='aluno';m.state.missing=true;expect(await readProfessionalBookingTerms(other,owner,m.client)).toBeNull();m.state.fail=true;await expect(readProfessionalBookingTerms(other,owner,m.client)).rejects.toThrow()})
it('controller busy lock and uncertain response retry preserve one request key',async()=>{const m=mock();await ready(m);m.state.fail=true;const pending=m.controller.saveTerms(input);expect(()=>m.controller.saveTerms(input)).toThrow();await expect(pending).rejects.toThrow();const first=m.calls.find(c=>c[0]==='rpc')![2] as {p_request_id:string};expect(m.last.profile).toBeNull();m.state.fail=false;await m.controller.refresh();await m.controller.saveTerms(input);const last=m.calls.filter(c=>c[0]==='rpc').at(-1)![2] as {p_request_id:string};expect(last.p_request_id).toBe(first.p_request_id)})
it('controller captures inputs before async work and new terms receive another key',async()=>{const m=mock();await ready(m);const body={...input};m.state.fail=true;const pending=m.controller.saveTerms(body);body.priceCents=30000;await expect(pending).rejects.toThrow();const first=m.calls.find(c=>c[0]==='rpc')![2] as {p_request_id:string};expect(first).toMatchObject({p_price_cents:20000});m.state.fail=false;await m.controller.refresh();await m.controller.saveTerms(body);const last=m.calls.filter(c=>c[0]==='rpc').at(-1)![2] as {p_request_id:string};expect(last.p_request_id).not.toBe(first.p_request_id)})
it('controller refuses unready admin student and disposed writes',async()=>{const m=mock();expect(()=>m.controller.saveTerms(input)).toThrow();for(const role of ['admin','aluno']){m.state.role=role;await m.controller.refresh();expect(()=>m.controller.saveTerms(input)).toThrow()}m.state.role='profissional';await m.controller.refresh();m.controller.dispose();expect(()=>m.controller.saveTerms(input)).toThrow();expect(m.calls.filter(c=>c[0]==='rpc')).toHaveLength(0)})
