import {it,expect} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {readBookingQuote,type BookingSlot} from './bookingQuote'
const owner='11111111-1111-4111-8111-111111111111',professional='22222222-2222-4222-8222-222222222222',terms='33333333-3333-4333-8333-333333333333'
const input:BookingSlot={professionalId:professional,day:'2026-10-10',hour:5}
function mock(){const state={id:owner,token:'one',role:'aluno',fail:false,missing:false,onResult:()=>{},override:{} as Record<string,unknown>},calls:unknown[][]=[]
 const base={professional_id:professional,day:'2026-10-10',hour:5,availability_version:2,terms_id:terms,terms_version:3,starts_at:'2026-10-10T08:00:00Z',ends_at:'2026-10-10T09:00:00Z',price_cents:20000,deposit_basis_points:2500,deposit_cents:5000,balance_cents:15000,free_cancel_hours:48,free_cancel_deadline:'2026-10-08T08:00:00Z',no_show_deposit_retained:true,quoted_at:'2026-10-07T18:00:00Z'}
 const client={auth:{getSession:async()=>({error:null,data:{session:{access_token:state.token,user:{id:state.id}}}}),getUser:async()=>({error:null,data:{user:{id:state.id,is_anonymous:false}}})},rpc:(name:string,args:Record<string,unknown>)=>({single:async()=>{calls.push(['rpc',name,{...args}]);state.onResult();return{error:state.fail?Error('Unavailable'):null,data:state.missing?null:{...base,...state.override}}}}),from:(table:string)=>{calls.push(['from',table]);return{select(){return this},eq(){return this},async maybeSingle(){return{error:null,data:{id:state.id,display_name:'Name',role:state.role,approved:false,created_at:'2026-10-07T18:00:00Z'}}}}}} as unknown as SupabaseClient<Database>
 return{state,calls,client,base}
}
it('reads server-validated slot with no client price student id or payment assertion',async()=>{const m=mock();const quote=await readBookingQuote(input,owner,m.client);expect(quote.deposit_cents).toBe(5000);expect(quote.balance_cents).toBe(15000);expect(m.calls.filter(c=>c[0]==='rpc')).toEqual([['rpc','quote_booking_slot',{p_professional_id:professional,p_day:'2026-10-10',p_hour:5}]])})
it('bad calendar hour or identifier rejected before SDK access',async()=>{const m=mock();for(const patch of [{hour:4},{hour:24},{hour:5.5},{professionalId:'bad'},{day:'2026-02-30'}])await expect(readBookingQuote({...input,...patch},owner,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('changed actor professional and admin cannot issue student quote RPC',async()=>{const m=mock();await expect(readBookingQuote(input,professional,m.client)).rejects.toThrow();for(const role of ['profissional','admin']){m.state.role=role;await expect(readBookingQuote(input,owner,m.client)).rejects.toThrow()}expect(m.calls.filter(c=>c[0]==='rpc')).toHaveLength(0)})
it('session change and absent unavailable slot never fabricate a quote',async()=>{const m=mock();m.state.onResult=()=>{m.state.token='two'};await expect(readBookingQuote(input,owner,m.client)).rejects.toThrow('Sessão alterada');const x=mock();x.state.missing=true;await expect(readBookingQuote(input,owner,x.client)).rejects.toThrow();x.state.missing=false;x.state.fail=true;await expect(readBookingQuote(input,owner,x.client)).rejects.toThrow()})
it('foreign target changed hour date and invalid versions are rejected',async()=>{for(const override of [{professional_id:owner},{day:'2026-10-11'},{hour:6},{availability_version:0},{terms_version:1.5},{terms_id:'bad'}]){const m=mock();m.state.override=override;await expect(readBookingQuote(input,owner,m.client)).rejects.toThrow()}})
it('amounts must reconcile with exact deposit rule and remaining balance',async()=>{for(const override of [{deposit_cents:5001},{balance_cents:15001},{price_cents:Number.MAX_SAFE_INTEGER+1},{deposit_basis_points:10001},{no_show_deposit_retained:false}]){const m=mock();m.state.override=override;await expect(readBookingQuote(input,owner,m.client)).rejects.toThrow()}})
it('timestamps must match local chosen hour one-hour duration and future quote',async()=>{for(const override of [{starts_at:'2026-10-10T07:00:00Z'},{ends_at:'2026-10-10T10:00:00Z'},{quoted_at:'2026-10-10T08:00:00Z'},{quoted_at:'2026-10-07 18:00:00'},{starts_at:'2026-10-10T08:00:00.001Z'}]){const m=mock();m.state.override=override;await expect(readBookingQuote(input,owner,m.client)).rejects.toThrow()}})
it('free cancellation deadline is exact and null only when no free window',async()=>{const m=mock();m.state.override={free_cancel_deadline:'2026-10-08T09:00:00Z'};await expect(readBookingQuote(input,owner,m.client)).rejects.toThrow();m.state.override={free_cancel_hours:0,free_cancel_deadline:null};expect((await readBookingQuote(input,owner,m.client)).free_cancel_deadline).toBeNull();m.state.override={free_cancel_hours:0};await expect(readBookingQuote(input,owner,m.client)).rejects.toThrow()})
it('23h block ends next day and selected slot is copied before await',async()=>{const m=mock();m.state.override={hour:23,starts_at:'2026-10-11T02:00:00Z',ends_at:'2026-10-11T03:00:00Z',free_cancel_deadline:'2026-10-09T02:00:00Z'};const body={...input,hour:23},pending=readBookingQuote(body,owner,m.client);body.day='2026-10-12';body.hour=5;expect((await pending).hour).toBe(23);expect(m.calls).toContainEqual(['rpc','quote_booking_slot',{p_professional_id:professional,p_day:'2026-10-10',p_hour:23}])})
