import {it,expect} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {readApprovedProfessionals} from './directory'
const id='11111111-1111-4111-8111-111111111111',provider='22222222-2222-4222-8222-222222222222'
function mock(){const state={token:'t1',signedIn:true,anonymous:false,fail:false,rows:[{professional_id:provider,display_name:'Profissional'}] as unknown[],onResult:()=>{}};const calls:unknown[][]=[];const client={auth:{getSession:async()=>({error:null,data:{session:state.signedIn?{access_token:state.token,user:{id}}:null}}),getUser:async()=>({error:null,data:{user:{id,is_anonymous:state.anonymous}}})},rpc:async(...args:unknown[])=>{calls.push(args);state.onResult();return{error:state.fail?Error('denied'):null,data:state.rows}}} as unknown as SupabaseClient<Database>;return{state,calls,client}}
it('catalog sends only bounded page and copies minimal response fields',async()=>{const m=mock();m.state.rows=[{professional_id:provider,display_name:'Nome',email:'private@example.invalid',role:'admin'}];expect(await readApprovedProfessionals(2,m.client)).toEqual([{professional_id:provider,display_name:'Nome'}]);expect(m.calls).toEqual([['list_approved_professionals',{p_page:2}]])})
it('invalid page makes no RPC',async()=>{const m=mock();for(const page of [0,-1,1.5,10001,NaN])await expect(readApprovedProfessionals(page,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('signed-out and anonymous Auth users cannot request catalog',async()=>{for(const anonymous of [false,true]){const m=mock();m.state.signedIn=anonymous;m.state.anonymous=anonymous;await expect(readApprovedProfessionals(1,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)}})
it('changed session discards otherwise valid catalog',async()=>{const m=mock();m.state.onResult=()=>{m.state.token='t2'};await expect(readApprovedProfessionals(1,m.client)).rejects.toThrow('Sessão alterada')})
it('server refusal cannot become empty success',async()=>{const m=mock();m.state.fail=true;await expect(readApprovedProfessionals(1,m.client)).rejects.toThrow()})
it('malformed identifiers names duplicate or oversized result rejected',async()=>{const m=mock();for(const rows of [[{professional_id:'invalid',display_name:'Nome'}],[{professional_id:provider,display_name:' '}],[{professional_id:provider,display_name:'X'.repeat(161)}],[null],Array(2).fill({professional_id:provider,display_name:'Nome'}),Array(21).fill({professional_id:provider,display_name:'Nome'})]){m.state.rows=rows;await expect(readApprovedProfessionals(1,m.client)).rejects.toThrow()}})
it('empty approved directory is a valid empty page',async()=>{const m=mock();m.state.rows=[];expect(await readApprovedProfessionals(1,m.client)).toEqual([])})
