import {expect,it} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {readEsgProjects,submitEsgProject,reviewEsgProject,type EsgProject} from './esgProjects'
import {createAccountSession,type AccountState} from './accountSession'
const owner='11111111-1111-4111-8111-111111111111',admin='22222222-2222-4222-8222-222222222222',project='33333333-3333-4333-8333-333333333333',key='44444444-4444-4444-8444-444444444444'
const body={category:'social' as const,title:'Title',description:'Description'}
const row:EsgProject={id:project,owner_id:owner,request_id:key,...body,status:'pending',version:1,submitted_at:'2026-10-08T12:00:00Z',reviewed_at:null,review_reason:null}
function mock(role='aluno'){
 const state={id:role==='admin'?admin:owner,role,token:'t1',anonymous:false,fail:false,override:null as EsgProject|null,list:[{...row}],onResult:()=>{},hold:null as Promise<void>|null}
 const calls:{name:string;args:Record<string,unknown>}[]=[],filters:unknown[][]=[],states:AccountState[]=[]
 const client={auth:{getSession:async()=>({error:null,data:{session:{access_token:state.token,user:{id:state.id}}}}),getUser:async()=>({error:null,data:{user:{id:state.id,is_anonymous:state.anonymous,user_metadata:{role:'admin'}}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},from:(_table:string)=>({select(){return this},eq(...args:unknown[]){filters.push(args);return this},order(){return this},async maybeSingle(){return{error:null,data:{id:state.id,display_name:'Name',role:state.role,approved:false,created_at:'2026-10-08T00:00:00Z'}}},async range(...args:unknown[]){filters.push(['range',...args]);state.onResult();return{error:state.fail?Error('denied'):null,data:state.list}}}),rpc:(name:string,args:Record<string,unknown>)=>({single:async()=>{calls.push({name,args});if(state.hold)await state.hold;state.onResult();const result=name==='submit_esg_project'?{...row,request_id:args.p_request_id,category:args.p_category,title:args.p_title,description:args.p_description}:{...row,status:args.p_decision,review_reason:args.p_reason,reviewed_at:'2026-10-08T13:00:00Z',version:2};return {error:state.fail?Error('denied'):null,data:state.override||result}}})} as unknown as SupabaseClient<Database>
 const controller=createAccountSession(client,s=>states.push(s));return{state,calls,filters,client,controller,states}
}
async function ready(m:ReturnType<typeof mock>){m.controller.start();for(let i=0;i<20;i++)await Promise.resolve();expect(m.states.at(-1)?.phase).toBe('ready')}
it('submission uses verified owner implicitly and sends only bounded project data and retry key',async()=>{const m=mock();await submitEsgProject({...body,title:' Title '},key,owner,m.client);expect(m.calls).toEqual([{name:'submit_esg_project',args:{p_request_id:key,p_category:'social',p_title:'Title',p_description:'Description'}}])})
it('invalid category blank oversized data anonymous accounts or wrong owner cannot mutate',async()=>{const m=mock();for(const input of [{...body,category:'unknown'},{...body,title:' '},{...body,description:'x'.repeat(6001)}])await expect(submitEsgProject(input as typeof body,key,owner,m.client)).rejects.toThrow();m.state.anonymous=true;await expect(submitEsgProject(body,key,owner,m.client)).rejects.toThrow();m.state.anonymous=false;await expect(submitEsgProject(body,key,admin,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('own reads filter by owner and admin scope requires trusted profile not user metadata',async()=>{const m=mock();await readEsgProjects(owner,'own',2,m.client);expect(m.filters).toContainEqual(['owner_id',owner]);expect(m.filters).toContainEqual(['range',20,39]);await expect(readEsgProjects(owner,'admin',1,m.client)).rejects.toThrow();const a=mock('admin');expect(await readEsgProjects(admin,'admin',1,a.client)).toHaveLength(1)})
it('foreign duplicated malformed and excessive rows are not displayed',async()=>{const m=mock();for(const list of [[{...row,owner_id:admin}],[row,row],[{...row,status:'approved',version:1}],Array(21).fill(row)]){m.state.list=list;await expect(readEsgProjects(owner,'own',1,m.client)).rejects.toThrow()}})
it('admin decision binds exact project version and reason while blocking self-review',async()=>{const m=mock('admin');await reviewEsgProject(row,'approved',' Checked ',admin,m.client);expect(m.calls[0]).toEqual({name:'review_esg_project',args:{p_project_id:project,p_expected_version:1,p_decision:'approved',p_reason:'Checked'}});await expect(reviewEsgProject({...row,owner_id:admin},'approved','Checked',admin,m.client)).rejects.toThrow();await expect(reviewEsgProject(row,'approved',' ',admin,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(1)})
it('changed sessions and mismatched mutation responses never report success',async()=>{const m=mock();m.state.override={...row,owner_id:admin};await expect(submitEsgProject(body,key,owner,m.client)).rejects.toThrow();m.state.override=null;m.state.onResult=()=>{m.state.token='t2'};await expect(submitEsgProject(body,key,owner,m.client)).rejects.toThrow('Sessão alterada');const a=mock('admin');a.state.override={...row,status:'rejected',version:2,reviewed_at:'2026-10-08T13:00:00Z',review_reason:'Checked'};await expect(reviewEsgProject(row,'approved','Checked',admin,a.client)).rejects.toThrow()})
it('submission replay may return the same already reviewed project without creating a new one',async()=>{const m=mock();m.state.override={...row,status:'approved',version:2,reviewed_at:'2026-10-08T13:00:00Z',review_reason:'Checked'};expect((await submitEsgProject(body,key,owner,m.client)).status).toBe('approved')})
it('controller rejects participant reviews and administrator submissions',async()=>{const m=mock();await ready(m);expect(()=>m.controller.reviewEsg(row,'approved','Checked')).toThrow();const a=mock('admin');await ready(a);expect(()=>a.controller.submitEsg(body)).toThrow();expect(m.calls).toHaveLength(0);expect(a.calls).toHaveLength(0)})
it('controller retains the request key after uncertain failure and copies the body',async()=>{const m=mock();await ready(m);m.state.fail=true;const input={...body};await expect(m.controller.submitEsg(input)).rejects.toThrow();const first=m.calls[0].args.p_request_id;await m.controller.refresh();m.state.fail=false;await m.controller.submitEsg(input);expect(m.calls[1].args.p_request_id).toBe(first);expect(m.states.at(-1)?.phase).toBe('ready')})
it('controller blocks simultaneous submissions and isolates mutable caller input',async()=>{const m=mock();await ready(m);let release!:()=>void;m.state.hold=new Promise<void>(resolve=>{release=resolve});const input={...body};const pending=m.controller.submitEsg(input);input.title='Changed after call';expect(()=>m.controller.submitEsg(body)).toThrow();for(let i=0;i<30;i++)await Promise.resolve();release();await pending;expect(m.calls).toHaveLength(1);expect(m.calls[0].args.p_title).toBe('Title')})
