import {it,expect} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {requestStudentLink,acceptStudentLink,revokeStudentLink,readMyStudentLink,readProfessionalLinks} from './links'
const student='00000000-0000-4000-8000-000000000001',provider='00000000-0000-4000-8000-000000000002',other='00000000-0000-4000-8000-000000000003'
function mock(id=student){const state={id,token:'t1',signedIn:true},calls:unknown[][]=[];let row={student_id:student,professional_id:provider,state:'pending',version:1,requested_at:'2026-10-05',accepted_at:null,revoked_at:null},fail=false,onResult=()=>{};const result=()=>{onResult();return{data:fail?null:row,error:fail?{message:'denied'}:null}};const builder={select(...a:unknown[]){calls.push(['select',...a]);return this},eq(...a:unknown[]){calls.push(['eq',...a]);return this},order(...a:unknown[]){calls.push(['order',...a]);return this},async range(...a:unknown[]){calls.push(['range',...a]);const r=result();return{...r,data:r.data?[r.data]:null}},async single(){return result()},async maybeSingle(){return result()}};const client={auth:{getSession:async()=>({error:null,data:{session:state.signedIn?{access_token:state.token,user:{id:state.id}}:null}}),getUser:async()=>({error:null,data:{user:{id:state.id,is_anonymous:false}}})},rpc:(...a:unknown[])=>{calls.push(['rpc',...a]);return builder},from:(...a:unknown[])=>{calls.push(['from',...a]);return builder}} as unknown as SupabaseClient<Database>;return{client,calls,state,setRow:(changes:Partial<typeof row>)=>row={...row,...changes},fail:()=>fail=true,onResult:(fn:()=>void)=>onResult=fn}}
it('request supplies only professional id; actor is verified and result must belong to pupil',async()=>{const m=mock();await requestStudentLink(provider,m.client);expect(m.calls[0]).toEqual(['rpc','request_student_link',{p_professional_id:provider}]);m.setRow({student_id:other});await expect(requestStudentLink(provider,m.client)).rejects.toThrow()})
it('accept binds student and expected version and requires active matching response',async()=>{const m=mock(provider);m.setRow({state:'active'});await acceptStudentLink(student,1,m.client);expect(m.calls[0]).toEqual(['rpc','accept_student_link',{p_student_id:student,p_expected_version:1}]);m.setRow({version:2});await expect(acceptStudentLink(student,1,m.client)).rejects.toThrow()})
it('revoke verifies state and participation rather than accepting unrelated result',async()=>{const m=mock();m.setRow({state:'revoked'});await revokeStudentLink(student,1,m.client);m.state.id=other;await expect(revokeStudentLink(student,1,m.client)).rejects.toThrow()})
it('invalid ids versions or pages never call a data operation',async()=>{const m=mock();await expect(requestStudentLink('../x',m.client)).rejects.toThrow();for(const v of [0,-1,1.2,Number.MAX_SAFE_INTEGER+1])await expect(acceptStudentLink(student,v,m.client)).rejects.toThrow();await expect(readProfessionalLinks(0,m.client)).rejects.toThrow();expect(m.calls).toEqual([])})
it('signed-out caller never invokes RPC',async()=>{const m=mock();m.state.signedIn=false;await expect(requestStudentLink(provider,m.client)).rejects.toThrow();expect(m.calls).toEqual([])})
it('session change rejects successful RPC response',async()=>{const m=mock();m.onResult(()=>{m.state.token='t2'});await expect(requestStudentLink(provider,m.client)).rejects.toThrow('Sessão alterada')})
it('own and professional reads bind actor and professional pagination is limited to twenty',async()=>{const s=mock();await readMyStudentLink(s.client);expect(s.calls).toContainEqual(['eq','student_id',student]);const p=mock(provider);await readProfessionalLinks(2,p.client);expect(p.calls).toContainEqual(['eq','professional_id',provider]);expect(p.calls).toContainEqual(['range',20,39])})
it('server denial never produces optimistic success',async()=>{const m=mock();m.fail();await expect(requestStudentLink(provider,m.client)).rejects.toThrow('Não foi possível pedir')})

it('request rejects revoked response instead of showing request success',async()=>{const m=mock();m.setRow({state:'revoked'});await expect(requestStudentLink(provider,m.client)).rejects.toThrow()})

it('request from old account UI cannot target a newly restored student account',async()=>{const m=mock();m.state.id=other;await expect(requestStudentLink(provider,m.client,student)).rejects.toThrow('Sessão alterada');expect(m.calls).toEqual([])})
