import {it,expect} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {readParticipantLinks,type ParticipantLink} from './participantLinks'
const student='11111111-1111-4111-8111-111111111111',professional='22222222-2222-4222-8222-222222222222',other='33333333-3333-4333-8333-333333333333'
const row:ParticipantLink={student_id:student,professional_id:professional,state:'pending',version:1,requested_at:'2026-10-06T00:00:00Z',accepted_at:null,revoked_at:null,participant_name:'Professional name'}
function mock(id=student){const state={id,token:'t1',signedIn:true,anonymous:false,fail:false,rows:[{...row}] as unknown[],onResult:()=>{}};const calls:unknown[][]=[];const client={auth:{getSession:async()=>({error:null,data:{session:state.signedIn?{access_token:state.token,user:{id:state.id}}:null}}),getUser:async()=>({error:null,data:{user:{id:state.id,is_anonymous:state.anonymous}}})},rpc:async(...args:unknown[])=>{calls.push(args);state.onResult();return{error:state.fail?Error('denied'):null,data:state.rows}}} as unknown as SupabaseClient<Database>;return{state,calls,client}}
it('student query sends only page and copies minimal fields, not extra private data',async()=>{const m=mock();m.state.rows=[{...row,email:'private@example.invalid',notes:'clinical'}];expect(await readParticipantLinks({id:student,role:'aluno'},1,m.client)).toEqual([row]);expect(m.calls).toEqual([['list_participant_links',{p_page:1}]])})
it('professional reads matching counterpart and chosen page without actor in payload',async()=>{const m=mock(professional);m.state.rows=[{...row,participant_name:'Student name'}];const rows=await readParticipantLinks({id:professional,role:'profissional'},2,m.client);expect(rows[0].participant_name).toBe('Student name');expect(m.calls).toEqual([['list_participant_links',{p_page:2}]])})
it('invalid role account or page causes no request',async()=>{const m=mock();for(const [id,role,page] of [[student,'admin',1],['invalid','aluno',1],[student,'aluno',2],[student,'profissional',0],[student,'profissional',10001],[student,'profissional',1.5]] as const)await expect(readParticipantLinks({id,role},page,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('signed out anonymous and changed account fail before RPC',async()=>{for(const kind of ['signedOut','anonymous','other']){const m=mock();if(kind==='signedOut')m.state.signedIn=false;if(kind==='anonymous')m.state.anonymous=true;if(kind==='other')m.state.id=other;await expect(readParticipantLinks({id:student,role:'aluno'},1,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)}})
it('session changed during response cannot display former names',async()=>{const m=mock();m.state.onResult=()=>{m.state.token='t2'};await expect(readParticipantLinks({id:student,role:'aluno'},1,m.client)).rejects.toThrow('Sessão alterada')})
it('unrelated student or professional rows are rejected',async()=>{const m=mock();m.state.rows=[{...row,student_id:other}];await expect(readParticipantLinks({id:student,role:'aluno'},1,m.client)).rejects.toThrow();const p=mock(professional);p.state.rows=[{...row,professional_id:other}];await expect(readParticipantLinks({id:professional,role:'profissional'},1,p.client)).rejects.toThrow()})
it('revoked relation suppresses name; approval or missing display name may yield null',async()=>{const m=mock();m.state.rows=[{...row,state:'revoked',revoked_at:'2026-10-06T01:00:00Z',participant_name:null}];expect((await readParticipantLinks({id:student,role:'aluno'},1,m.client))[0].participant_name).toBeNull();m.state.rows=[{...row,participant_name:null}];expect((await readParticipantLinks({id:student,role:'aluno'},1,m.client))[0].participant_name).toBeNull();m.state.rows=[{...row,state:'revoked',revoked_at:'2026-10-06T01:00:00Z'}];await expect(readParticipantLinks({id:student,role:'aluno'},1,m.client)).rejects.toThrow('Nome indisponível')})
it('invalid dates versions state names and identifiers are rejected',async()=>{const m=mock();for(const change of [{state:'root'},{state:'active',accepted_at:null},{state:'pending',revoked_at:'2026-10-06T01:00:00Z'},{state:'revoked',revoked_at:null},{requested_at:'bad-date'},{version:0},{professional_id:student},{professional_id:'invalid'},{participant_name:' '},{participant_name:'X'.repeat(161)}]){m.state.rows=[{...row,...change}];await expect(readParticipantLinks({id:student,role:'aluno'},1,m.client)).rejects.toThrow()}})
it('oversized and duplicated result is rejected; empty page stays empty',async()=>{const m=mock();m.state.rows=[];expect(await readParticipantLinks({id:student,role:'aluno'},1,m.client)).toEqual([]);m.state.rows=[row,row];await expect(readParticipantLinks({id:student,role:'aluno'},1,m.client)).rejects.toThrow();const p=mock(professional);p.state.rows=[row,row];await expect(readParticipantLinks({id:professional,role:'profissional'},1,p.client)).rejects.toThrow();p.state.rows=Array(21).fill(row);await expect(readParticipantLinks({id:professional,role:'profissional'},1,p.client)).rejects.toThrow()})
it('server refusal never becomes successful empty state',async()=>{const m=mock();m.state.fail=true;await expect(readParticipantLinks({id:student,role:'aluno'},1,m.client)).rejects.toThrow()})
