import {it,expect} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {createRankingDraft,readRankingDrafts,validateDraft,type DraftInput} from './rankingDrafts'
import {createAccountSession,type AccountState} from './accountSession'
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',request='33333333-3333-4333-8333-333333333333',id='44444444-4444-4444-8444-444444444444',stamp='2026-10-07T12:00:00Z'
const input:DraftInput={title:'Rules',notes:'Pending decision',referrals:'minimum_one',partnerServices:'floor_150',rating:'rounded',poolBasis:'tarifas_only'}
function mock(){
 const state={id:owner,token:'one',role:'admin',fail:false,onResult:()=>{},override:{} as Record<string,unknown>,rows:null as unknown[]|null,hold:null as Promise<void>|null},calls:unknown[][]=[],states:AccountState[]=[]
 const base={id,request_id:request,created_by:owner,created_at:stamp,title:input.title,notes:input.notes,referrals:input.referrals,partner_services:input.partnerServices,rating:input.rating,pool_basis:input.poolBasis}
 const client={auth:{getSession:async()=>({error:null,data:{session:{access_token:state.token,user:{id:state.id}}}}),getUser:async()=>({error:null,data:{user:{id:state.id,is_anonymous:false}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe:()=>{}}}})},rpc:(name:string,args:Record<string,unknown>)=>({single:async()=>{calls.push(['rpc',name,{...args}]);if(state.hold)await state.hold;state.onResult();return{error:state.fail?Error('Denied'):null,data:{...base,request_id:args.p_request_id,title:args.p_title,notes:args.p_notes,referrals:args.p_referrals,partner_services:args.p_partner_services,rating:args.p_rating,pool_basis:args.p_pool_basis,...state.override}}}}),from:(table:string)=>{calls.push(['from',table]);return{select(fields:string){calls.push(['select',fields]);return this},eq(){return this},order(){return this},async range(start:number,end:number){calls.push(['range',start,end]);state.onResult();return{error:state.fail?Error('Denied'):null,data:state.rows??[{...base,...state.override}]}},async maybeSingle(){return{error:null,data:{id:state.id,display_name:'Name',role:state.role,approved:false,created_at:stamp}}}}}} as unknown as SupabaseClient<Database>
 const controller=createAccountSession(client,s=>states.push(s));return{state,calls,client,controller,base,get last(){return states.at(-1)!}}
}
async function ready(m:ReturnType<typeof mock>){m.controller.start();for(let n=0;n<12;n++)await Promise.resolve();expect(m.last.phase).toBe('ready');m.calls.length=0}
it('requires explicit valid choices and bounded text before authentication or writes',async()=>{const m=mock();for(const change of [{title:''},{title:'a'.repeat(121)},{notes:'a'.repeat(2001)},{referrals:''},{partnerServices:'unknown'},{rating:'unknown'},{poolBasis:'unknown'}])await expect(createRankingDraft({...input,...change} as DraftInput,request,owner,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0);expect(validateDraft({...input,title:' Rules ',notes:' notes '})).toMatchObject({title:'Rules',notes:'notes'})})
it('trusted admin sends only immutable policy inputs with server-derived author',async()=>{const m=mock();await createRankingDraft(input,request,owner,m.client);expect(m.calls.filter(c=>c[0]==='rpc')).toEqual([['rpc','create_ranking_policy_draft',{p_request_id:request,p_title:'Rules',p_notes:'Pending decision',p_referrals:'minimum_one',p_partner_services:'floor_150',p_rating:'rounded',p_pool_basis:'tarifas_only'}]])})
it('different signed-in actor and nonadmin cannot invoke draft RPC',async()=>{const m=mock();await expect(createRankingDraft(input,request,other,m.client)).rejects.toThrow();m.state.role='aluno';await expect(createRankingDraft(input,request,owner,m.client)).rejects.toThrow();expect(m.calls.filter(c=>c[0]==='rpc')).toHaveLength(0)})
it('changed response session rejects saved result',async()=>{const m=mock();m.state.onResult=()=>{m.state.token='two'};await expect(createRankingDraft(input,request,owner,m.client)).rejects.toThrow('Sessão alterada')})
it('foreign author, request and mismatched policy cannot confirm a draft',async()=>{for(const override of [{created_by:other},{request_id:other},{partner_services:'cap_150'},{pool_basis:'tarifas_and_monthly'},{title:'Other'}]){const m=mock();m.state.override=override;await expect(createRankingDraft(input,request,owner,m.client)).rejects.toThrow()}})
it('malformed persisted draft and duplicate or oversized history are rejected',async()=>{for(const override of [{id:'bad'},{created_at:'bad'},{partner_services:'invalid'},{title:' Rules '}]){const m=mock();m.state.override=override;await expect(readRankingDrafts(owner,1,m.client)).rejects.toThrow()}const m=mock();m.state.rows=[m.base,m.base];await expect(readRankingDrafts(owner,1,m.client)).rejects.toThrow();m.state.rows=Array(21).fill(m.base);await expect(readRankingDrafts(owner,1,m.client)).rejects.toThrow()})
it('admin history includes other administrators with bounded pagination',async()=>{const m=mock();m.state.override={created_by:other};const rows=await readRankingDrafts(owner,2,m.client);expect(rows[0].created_by).toBe(other);expect(m.calls).toContainEqual(['range',20,39]);const x=mock();await expect(readRankingDrafts(owner,0,x.client)).rejects.toThrow();expect(x.calls).toHaveLength(0)})
it('controller prevents duplicate in-flight saves and reuses key after uncertain failure',async()=>{const m=mock();await ready(m);m.state.fail=true;const pending=m.controller.saveRankingDraft(input);expect(()=>m.controller.saveRankingDraft(input)).toThrow();await expect(pending).rejects.toThrow();const first=m.calls.find(c=>c[0]==='rpc')![2] as {p_request_id:string};expect(m.last.profile).toBeNull();m.state.fail=false;await m.controller.refresh();await m.controller.saveRankingDraft(input);const last=m.calls.filter(c=>c[0]==='rpc').at(-1)![2] as {p_request_id:string};expect(last.p_request_id).toBe(first.p_request_id)})
it('controller snapshots draft before asynchronous auth',async()=>{const m=mock();await ready(m);let done!:()=>void;m.state.hold=new Promise<void>(resolve=>done=resolve);const body={...input};const pending=m.controller.saveRankingDraft(body);body.partnerServices='cap_150';body.title='Changed';done();await pending;expect(m.calls.find(c=>c[0]==='rpc')![2]).toMatchObject({p_title:'Rules',p_partner_services:'floor_150'})})
it('controller rejects unready, nonadmin and disposed saves',async()=>{const m=mock();expect(()=>m.controller.saveRankingDraft(input)).toThrow();m.state.role='aluno';await ready(m);expect(()=>m.controller.saveRankingDraft(input)).toThrow();m.state.role='admin';await m.controller.refresh();m.controller.dispose();expect(()=>m.controller.saveRankingDraft(input)).toThrow();expect(m.calls.filter(c=>c[0]==='rpc')).toHaveLength(0)})
it('controller changed input creates a new immutable request after failure',async()=>{const m=mock();await ready(m);m.state.fail=true;await expect(m.controller.saveRankingDraft(input)).rejects.toThrow();const first=m.calls.find(c=>c[0]==='rpc')![2] as {p_request_id:string};m.state.fail=false;await m.controller.refresh();await m.controller.saveRankingDraft({...input,partnerServices:'cap_150'});const last=m.calls.filter(c=>c[0]==='rpc').at(-1)![2] as {p_request_id:string};expect(last.p_request_id).not.toBe(first.p_request_id);expect(last).toMatchObject({p_partner_services:'cap_150'})})
