import {it,expect} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {createTrainingPlan,readTrainingPlans,readTrainingNotices,markTrainingRead,type TrainingInput} from './trainingPlans'
import {createAccountSession,type AccountState} from './accountSession'
const student='11111111-1111-4111-8111-111111111111',professional='22222222-2222-4222-8222-222222222222',other='33333333-3333-4333-8333-333333333333',key='44444444-4444-4444-8444-444444444444',planId='55555555-5555-4555-8555-555555555555'
const link={student_id:student,professional_id:professional,state:'active',version:3,requested_at:'2026-10-06T12:00:00Z',accepted_at:'2026-10-06T12:01:00Z',revoked_at:null}
const plan={id:planId,request_id:key,student_id:student,professional_id:professional,link_version:3,title:'Title',content:'Text',created_at:'2026-10-06T12:00:00Z'}
const input:TrainingInput={studentId:student,linkVersion:3,requestId:key,title:'Title',content:'Text'}
function mock(role='profissional',approved=true){const state={id:role==='profissional'?professional:role==='admin'?other:student,token:'t1',role,approved,fail:false,override:false,plan:{...plan},notice:{plan_id:planId,recipient_id:student,created_at:plan.created_at,read_at:null as string|null},hold:null as Promise<void>|null,onResult:()=>{}};const calls:unknown[][]=[],states:AccountState[]=[];const client={auth:{getSession:async()=>({error:null,data:{session:{access_token:state.token,user:{id:state.id}}}}),getUser:async()=>({error:null,data:{user:{id:state.id,is_anonymous:false}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe:()=>{}}}})},from:(table:string)=>{calls.push(['from',table]);return{select(...args:unknown[]){calls.push(['select',...args]);return this},eq(...args:unknown[]){calls.push(['eq',...args]);return this},order(...args:unknown[]){calls.push(['order',...args]);return this},async range(...args:unknown[]){calls.push(['range',...args]);state.onResult();return{error:state.fail?Error('Denied'):null,data:[state.plan]}},async in(...args:unknown[]){calls.push(['in',...args]);state.onResult();return{error:null,data:[state.notice]}},async maybeSingle(){return{error:null,data:table==='profiles'?{id:state.id,role:state.role,approved:state.approved,display_name:'Name',created_at:'now'}:null}}}},rpc:(name:string,args:Record<string,unknown>)=>({single:async()=>{calls.push(['rpc',name,args]);if(state.hold)await state.hold;state.onResult();return{error:state.fail?Error('Denied'):null,data:name==='create_training_plan'?state.override?state.plan:{...plan,request_id:args.p_request_id,student_id:args.p_student_id,link_version:args.p_expected_link_version,title:args.p_title,content:args.p_content}:{...state.notice,read_at:'2026-10-06T13:00:00Z'}}}})} as unknown as SupabaseClient<Database>;const controller=createAccountSession(client,s=>states.push(s));return{state,calls,client,controller,get last(){return states.at(-1)!}}}
async function ready(m:ReturnType<typeof mock>){m.controller.start();for(let i=0;i<12;i++)await Promise.resolve();expect(m.last.phase).toBe('ready');m.calls.length=0}
it('create sends exact link version and idempotency key, with no client author role',async()=>{const m=mock();await createTrainingPlan({...input,title:' Title ',content:' Text '},professional,m.client);expect(m.calls).toEqual([['rpc','create_training_plan',{p_student_id:student,p_expected_link_version:3,p_request_id:key,p_title:'Title',p_content:'Text'}]])})
it('invalid identifiers version or bounded text make no mutation',async()=>{const m=mock();for(const change of [{studentId:'invalid'},{requestId:'invalid'},{linkVersion:0},{title:' '},{title:'X'.repeat(121)},{content:'X'.repeat(6001)}])await expect(createTrainingPlan({...input,...change},professional,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('changed author before RPC and changed session after RPC rejected',async()=>{const m=mock();m.state.id=other;await expect(createTrainingPlan(input,professional,m.client)).rejects.toThrow('Sessão alterada');expect(m.calls).toHaveLength(0);const x=mock();x.state.onResult=()=>{x.state.token='t2'};await expect(createTrainingPlan(input,professional,x.client)).rejects.toThrow('Sessão alterada')})
it('mismatched publication cannot be accepted as success',async()=>{const m=mock();m.state.override=true;for(const change of [{student_id:other},{professional_id:other},{link_version:99},{request_id:other},{content:'Other'},{created_at:'invalid'}]){m.state.plan={...plan,...change};await expect(createTrainingPlan(input,professional,m.client)).rejects.toThrow()}})
it('reads bind own participant and bound pagination, reject admin and another student row',async()=>{const m=mock();await readTrainingPlans({id:professional,role:'profissional'},2,m.client);expect(m.calls).toContainEqual(['eq','professional_id',professional]);expect(m.calls).toContainEqual(['range',20,39]);const a=mock('aluno');await readTrainingPlans({id:student,role:'aluno'},1,a.client);expect(a.calls).toContainEqual(['eq','student_id',student]);a.state.plan.student_id=other;await expect(readTrainingPlans({id:student,role:'aluno'},1,a.client)).rejects.toThrow();await expect(readTrainingPlans({id:other,role:'admin'},1,m.client)).rejects.toThrow()})
it('notification read selects only displayed plan ids and current pupil',async()=>{const m=mock('aluno');await readTrainingNotices([planId],student,m.client);expect(m.calls).toContainEqual(['eq','recipient_id',student]);expect(m.calls).toContainEqual(['in','plan_id',[planId]]);m.state.notice.recipient_id=other;await expect(readTrainingNotices([planId],student,m.client)).rejects.toThrow()})
it('mark read derives recipient server-side; malformed response does not signal read',async()=>{const m=mock('aluno');await markTrainingRead(planId,student,m.client);expect(m.calls).toEqual([['rpc','read_training_notification',{p_plan_id:planId}]]);m.state.notice.plan_id=other;await expect(markTrainingRead(planId,student,m.client)).rejects.toThrow()})
it('server failure produces no publication success',async()=>{const m=mock();m.state.fail=true;await expect(createTrainingPlan(input,professional,m.client)).rejects.toThrow();await expect(markTrainingRead(planId,professional,m.client)).rejects.toThrow()})
it('controller refuses pupil/admin/unapproved professional and nonactive or foreign relationship',async()=>{for(const [role,approved] of [['aluno',true],['admin',true],['profissional',false]] as const){const m=mock(role,approved);await ready(m);expect(()=>m.controller.publishTraining(link,'Title','Text')).toThrow();expect(m.calls).toHaveLength(0)}const p=mock();await ready(p);expect(()=>p.controller.publishTraining({...link,state:'pending'},'Title','Text')).toThrow();expect(()=>p.controller.publishTraining({...link,professional_id:other},'Title','Text')).toThrow()})
it('failed response retries same body with same key after account refresh',async()=>{const m=mock();await ready(m);m.state.fail=true;await expect(m.controller.publishTraining(link,'Title','Text')).rejects.toThrow();const first=m.calls.find(c=>c[0]==='rpc')![2] as {p_request_id:string};expect(m.last.phase).toBe('error');m.state.fail=false;await m.controller.refresh();await m.controller.publishTraining(link,'Title','Text');const rpc=m.calls.filter(c=>c[0]==='rpc');expect((rpc[1][2] as {p_request_id:string}).p_request_id).toBe(first.p_request_id);expect(m.last.phase).toBe('ready')})
it('controller snapshot and synchronous lock prevent duplicate or changed link targets',async()=>{const m=mock();await ready(m);let done!:()=>void;m.state.hold=new Promise<void>(r=>done=r);const row={...link},pending=m.controller.publishTraining(row,'Title','Text');row.student_id=other;row.version=99;expect(()=>m.controller.publishTraining(link,'Title','Text')).toThrow();await expect(m.controller.renameProfile('New')).rejects.toThrow();done();await pending;const rpc=m.calls.filter(c=>c[0]==='rpc');expect(rpc).toHaveLength(1);expect(rpc[0][2]).toMatchObject({p_student_id:student,p_expected_link_version:3})})
it('only pupil controller can acknowledge notice and server refusal clears owned state',async()=>{const p=mock();await ready(p);expect(()=>p.controller.readTraining(planId)).toThrow();const a=mock('aluno');await ready(a);await a.controller.readTraining(planId);expect(a.calls).toContainEqual(['rpc','read_training_notification',{p_plan_id:planId}]);a.state.fail=true;await expect(a.controller.readTraining(planId)).rejects.toThrow();expect(a.last.profile).toBeNull()})
