import {it,expect} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {completeTrainingPlan,readTrainingCompletions} from './trainingCompletions'
import {createAccountSession,type AccountState} from './accountSession'
const student='11111111-1111-4111-8111-111111111111',professional='22222222-2222-4222-8222-222222222222',id='33333333-3333-4333-8333-333333333333'
const plan={id,student_id:student,professional_id:professional,request_id:id,link_version:1,title:'Title',content:'Text',created_at:'2026-10-06T12:00:00Z'}
function mock(role='aluno'){
 const state={id:role==='aluno'?student:professional,token:'one',role,fail:false,row:{plan_id:id,student_id:student,completed_at:'2026-10-06T13:00:00Z'},onResult:()=>{},rows:null as unknown[]|null},calls:unknown[][]=[],states:AccountState[]=[]
 const result=async()=>{state.onResult();return{error:state.fail?Error('Denied'):null,data:state.row}}
 const client={auth:{getSession:async()=>({error:null,data:{session:{access_token:state.token,user:{id:state.id}}}}),getUser:async()=>({error:null,data:{user:{id:state.id,is_anonymous:false}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe:()=>{}}}})},rpc:(name:string,args:unknown)=>{calls.push(['rpc',name,args]);return{single:result}},from:(table:string)=>({select(fields:string){calls.push(['select',table,fields]);return this},eq(){return this},async maybeSingle(){return{error:null,data:{id:state.id,role:state.role,approved:true,display_name:'Name',created_at:plan.created_at}}},async in(field:string,ids:string[]){calls.push(['in',field,ids]);const r=await result();return{...r,data:state.rows??[state.row]}}})} as unknown as SupabaseClient<Database>
 const controller=createAccountSession(client,s=>states.push(s));return{client,state,calls,controller,get last(){return states.at(-1)!}}
}
it('completion RPC sends only publication id and validates server timestamp',async()=>{const m=mock();const row=await completeTrainingPlan(id,student,m.client);expect(row.completed_at).toBe(m.state.row.completed_at);expect(m.calls).toEqual([['rpc','complete_training_plan',{p_plan_id:id}]])})
it('bad identifier or changed expected account cannot mutate',async()=>{const m=mock();await expect(completeTrainingPlan('bad',student,m.client)).rejects.toThrow();await expect(completeTrainingPlan(id,professional,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('wrong student plan or invalid date cannot signal success',async()=>{for(const change of [{student_id:professional},{plan_id:professional},{completed_at:'invalid'}]){const m=mock();Object.assign(m.state.row,change);await expect(completeTrainingPlan(id,student,m.client)).rejects.toThrow()}})
it('server rejection and session change after request rejected',async()=>{const m=mock();m.state.fail=true;await expect(completeTrainingPlan(id,student,m.client)).rejects.toThrow();const x=mock();x.state.onResult=()=>{x.state.token='two'};await expect(completeTrainingPlan(id,student,x.client)).rejects.toThrow('Sessão alterada')})
it('participant read limits records to displayed owned publications',async()=>{for(const role of ['aluno','profissional']){const m=mock(role);await readTrainingCompletions([plan],{id:m.state.id,role},m.client);expect(m.calls).toContainEqual(['select','training_completions','plan_id,student_id,completed_at']);expect(m.calls).toContainEqual(['in','plan_id',[id]])}})
it('foreign duplicated oversized or admin plan lists cannot query',async()=>{for(const [plans,account] of [[[plan],{id:professional,role:'aluno'}],[[plan,plan],{id:student,role:'aluno'}],[Array(21).fill(plan),{id:student,role:'aluno'}],[[plan],{id:student,role:'admin'}]] as const){const m=mock();await expect(readTrainingCompletions([...plans],account,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)}})
it('unexpected student publication or repeated response rejected',async()=>{for(const rows of [[{...mock().state.row,student_id:professional}],[{...mock().state.row,plan_id:professional}],[mock().state.row,mock().state.row]]){const m=mock();m.state.rows=rows;await expect(readTrainingCompletions([plan],{id:student,role:'aluno'},m.client)).rejects.toThrow()}})
it('controller restricts completion to pupil and clears state on server refusal',async()=>{for(const role of ['profissional','admin','aluno']){const m=mock(role);m.controller.start();for(let n=0;n<12;n++)await Promise.resolve();expect(m.last.phase).toBe('ready');m.calls.length=0;if(role!=='aluno'){expect(()=>m.controller.completeTraining(id)).toThrow();expect(m.calls).toHaveLength(0)}else{m.state.fail=true;const pending=m.controller.completeTraining(id);expect(()=>m.controller.completeTraining(id)).toThrow();await expect(pending).rejects.toThrow();expect(m.last.profile).toBeNull()}m.controller.dispose()}})
