import {it,expect} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from './database.types'
import {parseWalletAmount,ensureOwnWallet,reserveWallet,cancelWallet,readOwnWallet} from './wallet'
import {createAccountSession,type AccountState} from './accountSession'
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',request='33333333-3333-4333-8333-333333333333',withdrawal='44444444-4444-4444-8444-444444444444',stamp='2026-10-07T11:00:00Z'
function mock(){
 const state={id:owner,token:'one',fail:false,account:{user_id:owner,available_cents:10000,reserved_cents:0,version:1,updated_at:stamp},row:{id:withdrawal,user_id:owner,request_id:request,amount_cents:4000,status:'reserved',created_at:stamp,cancelled_at:null as string|null},onResult:()=>{},onRange:()=>{},missing:false,rows:null as unknown[]|null,hold:null as Promise<void>|null},calls:unknown[][]=[],states:AccountState[]=[]
 const client={auth:{getSession:async()=>({error:null,data:{session:{access_token:state.token,user:{id:state.id}}}}),getUser:async()=>({error:null,data:{user:{id:state.id,is_anonymous:false}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe:()=>{}}}})},rpc:(name:string,args:Record<string,unknown>={})=>({single:async()=>{calls.push(['rpc',name,args]);if(state.hold)await state.hold;state.onResult();return{error:state.fail?Error('Denied'):null,data:name==='ensure_wallet_account'?state.account:name==='cancel_wallet_withdrawal'?{...state.row,status:'cancelled',cancelled_at:stamp}:{...state.row,request_id:args.p_request_id,amount_cents:args.p_amount_cents}}}}),from:(table:string)=>{calls.push(['from',table]);return{select(fields:string){calls.push(['select',fields]);return this},eq(field:string,value:string){calls.push(['eq',field,value]);return this},order(){return this},async range(start:number,end:number){calls.push(['range',start,end]);state.onRange();return{error:null,data:state.rows??[state.row]}},async maybeSingle(){return{error:null,data:table==='profiles'?{id:state.id,display_name:'Name',role:'aluno',approved:false,created_at:stamp}:state.missing?null:{...state.account}}}}}} as unknown as SupabaseClient<Database>
 const controller=createAccountSession(client,s=>states.push(s));return{state,calls,client,controller,get last(){return states.at(-1)!}}
}
async function ready(m:ReturnType<typeof mock>){m.controller.start();for(let n=0;n<12;n++)await Promise.resolve();expect(m.last.phase).toBe('ready');m.calls.length=0}
it('parse money exactly in cents with comma or dot and reject excess precision unsafe amounts',()=>{expect(parseWalletAmount('0,29')).toBe(29);expect(parseWalletAmount('100.01')).toBe(10001);expect(parseWalletAmount('90071992547409.91')).toBe(Number.MAX_SAFE_INTEGER);for(const value of ['0','-1','1.001','1e2','Infinity','1.2.3','90071992547409.92','1,000.00'])expect(()=>parseWalletAmount(value)).toThrow()})
it('reserve sends only key and integer cents with implicit owner',async()=>{const m=mock();await reserveWallet(request,4000,owner,m.client);expect(m.calls).toEqual([['rpc','reserve_wallet_withdrawal',{p_request_id:request,p_amount_cents:4000}]])})
it('invalid key amount and changed account cannot invoke mutation',async()=>{const m=mock();for(const amount of [0,-1,1.5,NaN,Number.MAX_SAFE_INTEGER+1])await expect(reserveWallet(request,amount,owner,m.client)).rejects.toThrow();await expect(reserveWallet('bad',1,owner,m.client)).rejects.toThrow();await expect(reserveWallet(request,1,other,m.client)).rejects.toThrow();expect(m.calls).toHaveLength(0)})
it('ensure verifies owner safe balances and session change after response',async()=>{const m=mock();m.state.account.user_id=other;await expect(ensureOwnWallet(owner,m.client)).rejects.toThrow();const x=mock();x.state.account.available_cents=Number.MAX_SAFE_INTEGER+1;await expect(ensureOwnWallet(owner,x.client)).rejects.toThrow();const y=mock();y.state.onResult=()=>{y.state.token='two'};await expect(ensureOwnWallet(owner,y.client)).rejects.toThrow('Sessão alterada')})
it('reserve rejects foreign owner bad status or malformed timestamp in response',async()=>{for(const change of [{user_id:other},{id:'bad'},{status:'paid'},{created_at:'bad'},{cancelled_at:stamp}]){const m=mock();Object.assign(m.state.row,change);await expect(reserveWallet(request,4000,owner,m.client)).rejects.toThrow()}})
it('cancel derives owner and requires returned cancellation for requested record',async()=>{const m=mock();await cancelWallet(withdrawal,owner,m.client);expect(m.calls).toEqual([['rpc','cancel_wallet_withdrawal',{p_withdrawal_id:withdrawal}]]);m.state.row.id=other;await expect(cancelWallet(withdrawal,owner,m.client)).rejects.toThrow()})
it('reads owner-bound page and checks account remained unchanged across queries',async()=>{const m=mock();await readOwnWallet(owner,2,m.client);expect(m.calls).toContainEqual(['eq','user_id',owner]);expect(m.calls).toContainEqual(['range',20,39]);m.state.onRange=()=>{m.state.account.version++};await expect(readOwnWallet(owner,1,m.client)).rejects.toThrow('Saldo alterado')})
it('foreign duplicate oversized and invalid paginated reads rejected',async()=>{const m=mock();m.state.row.user_id=other;await expect(readOwnWallet(owner,1,m.client)).rejects.toThrow();m.state.row.user_id=owner;m.state.rows=[m.state.row,m.state.row];await expect(readOwnWallet(owner,1,m.client)).rejects.toThrow();m.state.rows=Array(21).fill(m.state.row);await expect(readOwnWallet(owner,1,m.client)).rejects.toThrow();const x=mock();await expect(readOwnWallet(owner,0,x.client)).rejects.toThrow();expect(x.calls).toHaveLength(0)})
it('absent wallet does not fabricate a balance or reservation',async()=>{const m=mock();m.state.missing=true;expect(await readOwnWallet(owner,1,m.client)).toEqual({account:null,withdrawals:[]});expect(m.calls).not.toContainEqual(['from','wallet_withdrawals'])})
it('controller busy lock and failed-response retry retain one request key',async()=>{const m=mock();await ready(m);m.state.fail=true;const pending=m.controller.reserveWithdrawal(4000);expect(()=>m.controller.reserveWithdrawal(4000)).toThrow();await expect(pending).rejects.toThrow();const first=m.calls.find(c=>c[0]==='rpc')![2] as {p_request_id:string};expect(m.last.profile).toBeNull();m.state.fail=false;await m.controller.refresh();await m.controller.reserveWithdrawal(4000);const last=m.calls.filter(c=>c[0]==='rpc').at(-1)![2] as {p_request_id:string};expect(last.p_request_id).toBe(first.p_request_id)})
it('controller rejects foreign cancellations and captures original target before async work',async()=>{const m=mock();await ready(m);expect(()=>m.controller.cancelWithdrawal({id:withdrawal,user_id:other})).toThrow();let done!:()=>void;m.state.hold=new Promise<void>(resolve=>done=resolve);const row={id:withdrawal,user_id:owner},pending=m.controller.cancelWithdrawal(row);row.id=other;done();await pending;expect(m.calls).toContainEqual(['rpc','cancel_wallet_withdrawal',{p_withdrawal_id:withdrawal}])})
it('unready controller cannot initialize reserve or cancel a wallet',()=>{const m=mock();expect(()=>m.controller.initializeWallet()).toThrow();expect(()=>m.controller.reserveWithdrawal(1)).toThrow();expect(()=>m.controller.cancelWithdrawal({id:withdrawal,user_id:owner})).toThrow();expect(m.calls).toHaveLength(0);m.controller.dispose()})
