import {useEffect,useState,useId} from 'react'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {readAdminParticipantOverview,type ParticipantOverview} from '@/lib/supabase/adminOverview'
const money=(v:number)=>(v/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export default function AdminParticipantOverview({owner,disabled}:{owner:string;disabled:boolean}){
 const id=useId(),[draft,setDraft]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1),[reload,setReload]=useState(0),[rows,setRows]=useState<ParticipantOverview[]>([]),[loaded,setLoaded]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const identity=JSON.stringify([owner,query,page,reload])
 useEffect(()=>{let active=true;setRows([]);setLoaded('');setLoading(true);setError('');void readAdminParticipantOverview(owner,page,query).then(data=>{if(active){setRows(data);setLoaded(identity)}}).catch(()=>{if(active)setError('Não foi possível verificar os participantes. Atualize sua conta.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[owner,page,query,reload,identity])
 return <section aria-labelledby={`${id}-title`} className="space-y-4 rounded-xl border border-sky-200 p-4"><h2 id={`${id}-title`} className="text-lg font-semibold">Participantes — visão administrativa</h2><p>Consulta de cadastro, carteira e projetos registrados no Supabase. Esta tela não altera saldos ou aprova cadastros.</p>
 <form className="flex flex-wrap items-end gap-2" onSubmit={e=>{e.preventDefault();setRows([]);setLoaded('');setPage(1);setQuery(draft.trim());setReload(n=>n+1)}}><label htmlFor={`${id}-search`}>Nome ou identificador da conta<Input id={`${id}-search`} maxLength={120} value={draft} disabled={disabled||loading} onChange={e=>setDraft(e.target.value)}/></label><Button type="submit" disabled={disabled||loading}>Buscar</Button><Button type="button" variant="outline" disabled={disabled||loading} onClick={()=>{setDraft('');setQuery('');setPage(1);setReload(n=>n+1)}}>Mostrar todos</Button></form>
 {error&&<p role="alert">{error}</p>}{loading&&<p role="status">Consultando participantes…</p>}
 {loaded===identity&&(rows.length?<ul className="space-y-3">{rows.map(row=><li key={row.participant_id} className="space-y-2 rounded border p-3"><h3 className="font-semibold">{row.display_name||'Sem nome informado'}</h3><p className="break-all text-xs">Conta: {row.participant_id}</p><p>{row.participant_role==='aluno'?'Aluno':`Profissional — ${row.professional_approved?'aprovado':'aprovação pendente'}`}</p><p>Cadastro: {new Date(row.joined_at).toLocaleDateString('pt-BR')}</p>{row.wallet_initialized?<p>Carteira: {money(row.available_cents!)} disponíveis · {money(row.reserved_cents!)} reservados. Reservas não confirmam pagamento ou saque concluído.</p>:<p>Carteira ainda não inicializada. Saldo não informado.</p>}<p>Projetos ESG: {row.esg_pending} em análise · {row.esg_approved} aprovados · {row.esg_rejected} recusados.</p><p className="text-sm">Projetos aprovados não equivalem automaticamente a metas financeiras cumpridas.</p><p className="text-sm text-slate-600">Consulta: {new Date(row.checked_at).toLocaleString('pt-BR')}</p></li>)}</ul>:<p>Nenhum participante encontrado nesta página.</p>)}
 <p className="rounded bg-slate-50 p-3 text-sm">Tarifas realizadas, serviços concluídos, pontuação mensal, posição no ranking e cashback fechado ainda não estão integrados a esta consulta. Nenhum valor é estimado para esses campos.</p>
 <div className="flex flex-wrap items-center gap-2"><Button type="button" variant="outline" disabled={disabled||loading||!!error||page<=1} onClick={()=>setPage(n=>n-1)}>Anterior</Button><span>Página {page}</span><Button type="button" variant="outline" disabled={disabled||loading||!!error||rows.length<20||page>=10000} onClick={()=>setPage(n=>n+1)}>Próxima</Button><Button type="button" variant="outline" disabled={disabled||loading} onClick={()=>setReload(n=>n+1)}>Atualizar consulta</Button></div>
 </section>
}
