import {useEffect,useState} from 'react'
import {Button} from '@/components/ui/button'
import {readBookingQuote,type BookingQuote,type BookingSlot} from '@/lib/supabase/bookingQuote'
function money(value:number){const cents=BigInt(value);return `R$ ${new Intl.NumberFormat('pt-BR').format(cents/100n)},${String(cents%100n).padStart(2,'0')}`}
function time(value:string){return new Date(value).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'})}
export default function BookingSlotReview({owner,slot,disabled,onClose}:{owner:string;slot:BookingSlot;disabled:boolean;onClose:()=>void}){
 const [quote,setQuote]=useState<BookingQuote|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[reload,setReload]=useState(0),[loaded,setLoaded]=useState('')
 const identity=[owner,slot.professionalId,slot.day,slot.hour].join(':')
 useEffect(()=>{let active=true;setQuote(null);setLoaded('');setLoading(true);setError('');void readBookingQuote({professionalId:slot.professionalId,day:slot.day,hour:slot.hour},owner).then(result=>{if(active){setQuote(result);setLoaded(identity)}}).catch(()=>{if(active)setError('O horário ou as condições podem ter mudado. Atualize a consulta ou escolha outro horário.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[owner,slot.professionalId,slot.day,slot.hour,identity,reload])
 return <section className="space-y-3 rounded-lg border border-blue-300 bg-blue-50 p-4" aria-label="Conferir atendimento"><h3 className="font-semibold">Conferir atendimento</h3>{loading&&<p role="status">Conferindo horário e condições…</p>}{error&&<p role="alert">{error}</p>}{quote&&loaded===identity&&<><p>{time(quote.starts_at)} até {time(quote.ends_at)} — horário de Brasília.</p><dl className="space-y-1"><div><dt>Preço total</dt><dd className="font-semibold">{money(quote.price_cents)}</dd></div><div><dt>Sinal para futura confirmação</dt><dd className="font-semibold">{money(quote.deposit_cents)}</dd></div><div><dt>Restante do atendimento</dt><dd>{money(quote.balance_cents)}</dd></div></dl>{quote.free_cancel_deadline?<p>Cancelamento sem multa até {time(quote.free_cancel_deadline)}.{Date.parse(quote.free_cancel_deadline)<=Date.parse(quote.quoted_at)&&' Esse prazo já havia terminado no momento desta consulta.'}</p>:<p>Esta condição não oferece prazo de cancelamento gratuito.</p>}<p>Em caso de não comparecimento, o sinal será retido pelo profissional.</p><p className="text-sm">Condições na versão {quote.terms_version}. Consulta realizada em {time(quote.quoted_at)}.</p><p className="font-medium">O horário ainda não está reservado. O pagamento do sinal e a confirmação do agendamento estão em preparação.</p></>}
 <div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={disabled||loading} onClick={()=>setReload(n=>n+1)}>Atualizar cotação</Button><Button type="button" variant="outline" disabled={disabled} onClick={onClose}>Fechar conferência</Button></div></section>
}
