import {useEffect,useRef,useState} from 'react'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {readOwnBookingTerms,readProfessionalBookingTerms,parseDepositPercentage,depositCents,type BookingTerms as Terms,type BookingTermsInput} from '@/lib/supabase/bookingTerms'
import {parseWalletAmount} from '@/lib/supabase/wallet'
function decimal(value:number){const cents=BigInt(value);return `${cents/100n},${String(cents%100n).padStart(2,'0')}`}
function money(value:number){const cents=BigInt(value);return `R$ ${new Intl.NumberFormat('pt-BR').format(cents/100n)},${String(cents%100n).padStart(2,'0')}`}
function summary(terms:Terms){return <div className="space-y-1"><p>Preço: <strong>{money(terms.price_cents)}</strong></p><p>Sinal: {decimal(terms.deposit_basis_points)}% — <strong>{money(terms.deposit_cents)}</strong></p><p>{terms.free_cancel_hours===0?'Sem prazo de cancelamento gratuito.':`Cancelamento sem multa até ${terms.free_cancel_hours} horas antes do atendimento.`}</p><p>Sinal retido pelo profissional em caso de não comparecimento.</p><p className="text-sm">Versão {terms.version}. Condições para futura reserva; nenhuma cobrança realizada.</p></div>}
export default function BookingTerms({owner,professionalId,disabled,onSave}:{owner:string;professionalId?:string;disabled:boolean;onSave?:(input:BookingTermsInput)=>Promise<void>}){
 const [terms,setTerms]=useState<Terms|null>(null),[loaded,setLoaded]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[reload,setReload]=useState(0),[price,setPrice]=useState(''),[percentage,setPercentage]=useState(''),[cancel,setCancel]=useState(''),[saving,setSaving]=useState(false)
 const lock=useRef(false),mounted=useRef(true),identity=owner+':'+(professionalId??'own')
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[])
 useEffect(()=>{let active=true;setTerms(null);setLoaded('');setPrice('');setPercentage('');setCancel('');setError('');setLoading(true);const read=professionalId?readProfessionalBookingTerms(professionalId,owner):readOwnBookingTerms(owner);void read.then(current=>{if(active){setTerms(current);setLoaded(identity);if(current){setPrice(decimal(current.price_cents));setPercentage(decimal(current.deposit_basis_points));setCancel(String(current.free_cancel_hours))}}}).catch(()=>{if(active)setError('Não foi possível verificar as condições. Atualize antes de continuar.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[owner,professionalId,identity,reload])
 let preview:number|null=null;try{preview=depositCents(parseWalletAmount(price),parseDepositPercentage(percentage))}catch{/* Incomplete input has no quote. */}
 const blocked=disabled||loading||saving||loaded!==identity
 async function save(){if(lock.current||blocked||!onSave||professionalId)return;let input:BookingTermsInput;try{if(!/^\d{1,3}$/.test(cancel))throw Error();input={expectedVersion:terms?.version??0,priceCents:parseWalletAmount(price),depositBasisPoints:parseDepositPercentage(percentage),freeCancelHours:Number(cancel)};if(input.freeCancelHours>720)throw Error();depositCents(input.priceCents,input.depositBasisPoints)}catch{setError('Preencha preço, sinal entre 0,01% e 100% e prazo de 0 a 720 horas. O sinal deve resultar em pelo menos R$ 0,01.');return}lock.current=true;setSaving(true);setError('');try{await onSave(input);if(mounted.current)setReload(n=>n+1)}catch{if(mounted.current)setError('As condições não foram confirmadas. Atualize sua conta e confira a versão antes de repetir.')}finally{lock.current=false;if(mounted.current)setSaving(false)}}
 return <section className="space-y-3 rounded border p-4" aria-label="Condições de atendimento"><h3 className="font-semibold">Condições de atendimento</h3>{loading&&<p role="status">Verificando condições…</p>}{error&&<p role="alert">{error}</p>}{loaded===identity&&(terms?summary(terms):<p>O profissional ainda não configurou as condições.</p>)}
 {!professionalId&&onSave&&<form className="space-y-2" onSubmit={e=>{e.preventDefault();void save()}}><p>Cada salvamento cria uma versão. O aluno pode consultar as condições, mas ainda não pode pagar ou confirmar uma reserva.</p><label className="block">Preço do atendimento (R$)<Input required inputMode="decimal" maxLength={18} disabled={blocked} value={price} onChange={e=>setPrice(e.target.value)}/></label><label className="block">Sinal (%)<Input required inputMode="decimal" maxLength={6} disabled={blocked} value={percentage} onChange={e=>setPercentage(e.target.value)}/></label><label className="block">Prazo de cancelamento sem multa (horas)<Input required inputMode="numeric" maxLength={3} disabled={blocked} value={cancel} onChange={e=>setCancel(e.target.value)}/></label><p>Use 0 para não oferecer prazo gratuito. A cobrança por cancelamento fora do prazo será definida na integração de reservas.</p>{preview!==null&&<p>Sinal calculado: <strong>{money(preview)}</strong></p>}<p>Em caso de não comparecimento, o sinal será retido pelo profissional.</p><Button type="submit" disabled={blocked||preview===null||!cancel}>Salvar nova versão das condições</Button></form>}
 <Button type="button" variant="outline" disabled={disabled||loading||saving} onClick={()=>setReload(n=>n+1)}>Atualizar condições</Button></section>
}
