import {useEffect,useRef,useState} from 'react'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {specialties,readOwnApplication,readApplicationQueue,type Specialty,type Application} from '@/lib/supabase/applications'
import type {OwnProfile} from '@/lib/supabase/profiles'
type Props={account:OwnProfile;disabled:boolean;onSubmit:(specialty:Specialty,credential:string)=>Promise<void>;onReview:(row:Application,decision:'approved'|'rejected',reason:string)=>Promise<void>}
export default function ProfessionalApplications({account,disabled,onSubmit,onReview}:Props){
 const [rows,setRows]=useState<Application[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[page,setPage]=useState(1),[reload,setReload]=useState(0),[owner,setOwner]=useState<string|null>(null)
 const [specialty,setSpecialty]=useState<Specialty>('educacao_fisica'),[credential,setCredential]=useState(''),[review,setReview]=useState<{row:Application;decision:'approved'|'rejected'}|null>(null),[reason,setReason]=useState(''),[checked,setChecked]=useState(false),[sending,setSending]=useState(false)
 const lock=useRef(false),mounted=useRef(true),admin=account.role==='admin'
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[])
 useEffect(()=>{setPage(1)},[account.id])
 useEffect(()=>{let active=true;setRows([]);setOwner(null);setReview(null);setReason('');setChecked(false);setError('');setLoading(true)
  const task=admin?readApplicationQueue(account.id,page):readOwnApplication(account.id).then(row=>row?[row]:[])
  task.then(data=>{if(active){setRows(data);setOwner(account.id)}}).catch(()=>{if(active)setError('Não foi possível carregar as solicitações.')}).finally(()=>{if(active)setLoading(false)})
  return()=>{active=false}
 },[account.id,account.role,admin,page,reload])
 async function act(task:()=>Promise<void>){if(lock.current||disabled)return;lock.current=true;setSending(true);setError('');try{await task();if(mounted.current)setReload(n=>n+1)}catch{if(mounted.current)setError('Não foi possível concluir. Atualize sua conta e verifique a solicitação.')}finally{lock.current=false;if(mounted.current)setSending(false)}}
 const blocked=disabled||sending||loading||owner!==account.id,own=rows[0]
 return <section className="space-y-3 rounded-lg border p-4" aria-label={admin?'Análise de acesso profissional':'Acesso profissional'}><h2 className="text-lg font-semibold">{admin?'Análise de acesso profissional':'Acesso profissional'}</h2>
  {error&&<p role="alert">{error}</p>}{loading&&<p role="status">Carregando solicitações…</p>}
  {!loading&&owner===account.id&&(admin?<><p>Confira a identidade e a qualificação antes de aprovar. Aprovação não verifica registros profissionais automaticamente.</p>{rows.length?<ul className="space-y-3">{rows.map(row=><li key={row.applicant_id} className="space-y-2 rounded border p-3"><p className="font-semibold">{row.applicant_name}</p><p>{specialties[row.specialty as Specialty]}</p><p>Registro ou qualificação: {row.credential}</p><p>Enviado em {new Date(row.requested_at).toLocaleString('pt-BR')}</p><div className="flex gap-2"><Button type="button" disabled={blocked} onClick={()=>{setReview({row,decision:'approved'});setReason('');setChecked(false)}}>Aprovar acesso</Button><Button type="button" variant="outline" disabled={blocked} onClick={()=>{setReview({row,decision:'rejected'});setReason('');setChecked(false)}}>Recusar</Button></div></li>)}</ul>:<p>Nenhuma solicitação pendente nesta página.</p>}
   {review&&<form className="space-y-3 rounded border p-3" onSubmit={event=>{event.preventDefault();if(review.decision==='approved'&&!checked)return;void act(()=>onReview(review.row,review.decision,reason))}}><p>{review.decision==='approved'?'Aprovar':'Recusar'} o acesso de {review.row.applicant_name}?</p><label className="block">Motivo da decisão<textarea className="mt-1 block w-full rounded border p-2" required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} disabled={blocked}/></label>{review.decision==='approved'&&<label className="flex items-start gap-2"><input type="checkbox" required checked={checked} onChange={e=>setChecked(e.target.checked)} disabled={blocked}/>Conferi a identidade, a qualificação e o registro profissional quando aplicável.</label>}<div className="flex gap-2"><Button type="submit" disabled={blocked||!reason.trim()||review.decision==='approved'&&!checked}>Confirmar decisão</Button><Button type="button" variant="outline" disabled={blocked} onClick={()=>setReview(null)}>Cancelar</Button></div></form>}
   <div className="flex items-center gap-2"><Button type="button" variant="outline" disabled={blocked||page<=1} onClick={()=>setPage(n=>n-1)}>Anterior</Button><span>Página {page}</span><Button type="button" variant="outline" disabled={blocked||rows.length<20||page>=10000} onClick={()=>setPage(n=>n+1)}>Próxima</Button></div>
  </>:<>{own&&<div className="space-y-2"><p>Situação: {own.status==='pending'?'Em análise':own.status==='approved'?'Aprovado':'Recusado'}</p><p>Área: {specialties[own.specialty as Specialty]}</p>{own.review_reason&&<p>Motivo: {own.review_reason}</p>}</div>}{account.role==='profissional'&&account.approved?<p>Seu acesso profissional está aprovado.</p>:own?.status==='pending'?<p>Aguarde a análise administrativa. Você continua com o acesso atual.</p>:<form className="space-y-3" onSubmit={e=>{e.preventDefault();void act(()=>onSubmit(specialty,credential))}}><p>Informe sua área e qualificação para análise. Não envie documentos pessoais ou dados de saúde neste campo.</p><label className="block">Área<select className="mt-1 block w-full rounded border bg-white p-2" value={specialty} onChange={e=>setSpecialty(e.target.value as Specialty)} disabled={blocked}>{Object.entries(specialties).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="block">Registro profissional ou referência de qualificação<Input required maxLength={160} value={credential} onChange={e=>setCredential(e.target.value)} disabled={blocked}/></label><Button type="submit" disabled={blocked||!credential.trim()}>{own?.status==='rejected'?'Enviar nova solicitação':'Solicitar acesso profissional'}</Button></form>}</>)}
  <Button type="button" variant="outline" disabled={disabled||loading||sending} onClick={()=>setReload(n=>n+1)}>Atualizar solicitações</Button>
 </section>
}
