import {useEffect,useRef,useState} from 'react'
import {Button} from '@/components/ui/button'
import {readOwnAvailability,monthDays,shiftMonth,saoPauloToday,lastAvailabilityDay,saoPauloHour,type AvailabilityDay,type AvailabilityInput} from '@/lib/supabase/availability'
export default function ProfessionalAvailability({owner,disabled,selectedDay,onSelectDay,onSave}:{owner:string;disabled:boolean;selectedDay:string;onSelectDay:(day:string)=>void;onSave:(input:AvailabilityInput)=>Promise<void>}){
 const month=selectedDay.slice(0,8)+'01',today=saoPauloToday(),minMonth=today.slice(0,8)+'01',maxMonth=shiftMonth(minMonth,12),days=monthDays(month),lastDay=lastAvailabilityDay(today),currentHour=saoPauloHour()
 const [rows,setRows]=useState<AvailabilityDay[]>([]),[loaded,setLoaded]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[reload,setReload]=useState(0),[saving,setSaving]=useState(false)
 const lock=useRef(false),mounted=useRef(true)
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[])
 useEffect(()=>{let active=true;setRows([]);setLoaded('');setLoading(true);setError('');void readOwnAvailability(owner,month).then(result=>{if(active){setRows(result);setLoaded(owner+month)}}).catch(()=>{if(active)setError('Não foi possível verificar sua agenda. Atualize antes de editar.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[owner,month,reload])
 const current=rows.find(row=>row.day===selectedDay),available=current?.available_hours??[],released=current?.released??false,blocked=disabled||loading||saving||loaded!==owner+month
 async function save(nextHours:number[],nextReleased:boolean){if(lock.current||blocked||selectedDay<today)return;lock.current=true;setSaving(true);setError('');const input={day:selectedDay,expectedVersion:current?.version??0,hours:[...nextHours],released:nextReleased};try{await onSave(input);if(mounted.current)setReload(n=>n+1)}catch{if(mounted.current)setError('A alteração não foi confirmada. Atualize sua conta e confira a agenda antes de repetir.')}finally{lock.current=false;if(mounted.current)setSaving(false)}}
 function navigate(offset:number){const next=shiftMonth(month,offset);onSelectDay(next===minMonth?today:next)}
 const weekday=new Date(days[0]+'T12:00:00Z').getUTCDay()
 return <section className="space-y-3 rounded-lg border p-4" aria-label="Agenda profissional"><h2 className="text-lg font-semibold">Sua agenda</h2><p>Horários de Brasília. Blocos individuais de 1 hora, das 05h à meia-noite. Clique para liberar ou bloquear um horário; use “Liberar Dia” para exibir a disponibilidade aos alunos.</p><p>Esta etapa mostra disponibilidade. Não confirma consultas, recebe sinal ou gera pontos.</p>{error&&<p role="alert">{error}</p>}{loading&&<p role="status">Verificando agenda…</p>}
 <div className="flex items-center justify-between gap-2"><Button type="button" variant="outline" disabled={disabled||saving||month<=minMonth} onClick={()=>navigate(-1)}>Anterior</Button><span>{new Date(month+'T12:00:00Z').toLocaleDateString('pt-BR',{month:'long',year:'numeric',timeZone:'America/Sao_Paulo'})}</span><Button type="button" variant="outline" disabled={disabled||saving||month>=maxMonth} onClick={()=>navigate(1)}>Próximo</Button></div>
 <div className="grid grid-cols-7 gap-1">{['D','S','T','Q','Q','S','S'].map((label,i)=><span className="text-center" key={i} aria-hidden="true">{label}</span>)}{Array.from({length:weekday},(_,i)=><span key={'space'+i}/>)}{days.map(day=>{const data=rows.find(row=>row.day===day);return <button key={day} type="button" disabled={disabled||loading||saving||day<today||day>lastDay} aria-pressed={day===selectedDay} aria-label={`${day.slice(8)} ${data?.released?'liberado':'não liberado'}`} className={`rounded border p-2 text-sm ${day===selectedDay?'bg-lime-200':''} ${data?.released?'border-green-700':'border-slate-300'}`} onClick={()=>onSelectDay(day)}>{Number(day.slice(8))}{data?.released&&<span className="block text-xs">Livre</span>}</button>})}</div>
 <h3 className="font-semibold">{new Date(selectedDay+'T12:00:00Z').toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'})} — {released?'Dia liberado':'Dia não liberado'}</h3>
 <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{Array.from({length:19},(_,n)=>n+5).map(hour=>{const free=available.includes(hour);return <Button key={hour} type="button" variant={free?'default':'outline'} disabled={blocked||selectedDay<today||selectedDay>lastDay||selectedDay===today&&hour<=currentHour} aria-pressed={free} onClick={()=>{const next=free?available.filter(h=>h!==hour):[...available,hour].sort((a,b)=>a-b);void save(next,released&&next.length>0)}}>{String(hour).padStart(2,'0')}:00–{hour===23?'00':String(hour+1).padStart(2,'0')}:00 · {free?'Livre':'Bloqueado'}</Button>})}</div>
 <div className="flex flex-wrap gap-2"><Button type="button" disabled={blocked||selectedDay<today||!available.length} onClick={()=>void save(available,!released)}>{released?'Retirar dia da busca':'Liberar Dia'}</Button><Button type="button" variant="outline" disabled={disabled||loading||saving} onClick={()=>setReload(n=>n+1)}>Atualizar agenda</Button></div><p>Ao bloquear o último horário, o dia sai da busca. Aulas coletivas, duração variável, sinal e cancelamentos serão integrados nas próximas etapas.</p>
 </section>
}
