import {useEffect,useState,useRef} from 'react'
import EsgCashbackSimulator from './EsgCashbackSimulator'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {readRankingDrafts,validateNewDraft as validateDraft,type RankingDraft,type DraftInput} from '@/lib/supabase/rankingDrafts'
import {calculateWellnessRankingPreview,APPROVED_PARTNER_SERVICES,type RankingPolicy} from '@/lib/rankingRules'
const referrals={minimum_one:'Pelo menos 1: máx(indicações, 1)',plus_one:'Indicações + 1',legacy_divisor_18:'Indicações ÷ 18 + 1'} as const
const services={actual:'Serviços realizados',floor_150:'Piso de 150 serviços',cap_150:'Teto de 150 serviços'} as const
const ratings={rounded:'Avaliação arredondada',exact:'Avaliação sem arredondamento'} as const
const bases={tarifas_only:'Somente tarifas',tarifas_and_monthly:'Tarifas e mensalidades',weighted_tarifas_monthly:'Tarifas e mensalidades ponderadas (pesos pendentes)'} as const
function example(ref:RankingPolicy['referrals'],rating:RankingPolicy['rating'],count:number){return calculateWellnessRankingPreview({version:'wellness-cap-150-2026-10-07',referrals:ref,rating},{id:'exemplo',multiplier:2,completedEligibleServices:count,validatedReferrals:3,rating:4.5,seniorityMonths:12,previousPoints:0,partnerPro:true,joinedAt:'2026-01-01T00:00:00Z'}).monthlyPoints}
export default function RankingPolicyDrafts({owner,disabled,onSave}:{owner:string;disabled:boolean;onSave:(input:DraftInput)=>Promise<void>}){
 const [title,setTitle]=useState(''),[notes,setNotes]=useState(''),[ref,setRef]=useState<DraftInput['referrals']|''>(''),[rating,setRating]=useState<DraftInput['rating']|''>(''),[basis,setBasis]=useState<DraftInput['poolBasis']|''>(''),[rows,setRows]=useState<RankingDraft[]>([]),[page,setPage]=useState(1),[reload,setReload]=useState(0),[loadedOwner,setLoadedOwner]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const lock=useRef(false),mounted=useRef(true)
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[])
 useEffect(()=>{let active=true;setRows([]);setLoadedOwner(null);setLoading(true);setError('');void readRankingDrafts(owner,page).then(result=>{if(active){setRows(result);setLoadedOwner(owner)}}).catch(()=>{if(active)setError('Não foi possível verificar o histórico. Atualize sua conta.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[owner,page,reload])
 async function save(){if(lock.current||disabled||loading||loadedOwner!==owner)return;let input:DraftInput;try{input=validateDraft({title,notes,referrals:ref as DraftInput['referrals'],partnerServices:APPROVED_PARTNER_SERVICES,rating:rating as DraftInput['rating'],poolBasis:basis as DraftInput['poolBasis']})}catch{setError('Preencha o título e escolha todas as regras.');return}lock.current=true;setSaving(true);setError('');try{await onSave(input);if(mounted.current){setTitle('');setNotes('');setReload(n=>n+1)}}catch{if(mounted.current)setError('Não foi possível confirmar o rascunho. Atualize o histórico antes de repetir.')}finally{lock.current=false;if(mounted.current)setSaving(false)}}
 const blocked=disabled||loading||saving||loadedOwner!==owner
 function select<T extends string>(label:string,value:T|'',options:Record<T,string>,change:(value:T|'')=>void){return <label className="block">{label}<select className="block w-full rounded border p-2" required disabled={blocked} value={value} onChange={e=>change(e.target.value as T|'')}><option value="">Escolha uma opção</option>{Object.entries(options).map(([key,label])=><option key={key} value={key}>{String(label)}</option>)}</select></label>}
 return <section aria-label="Rascunhos de ranking e cashback" className="space-y-3 rounded-lg border p-4"><h2 className="text-lg font-semibold">Regras em revisão</h2><p>Cada salvamento cria um rascunho imutável. Nenhuma opção ativa o ranking ou credita cashback. A base do pool é uma proposta; percentual, pesos, elegibilidade e fechamento ainda exigem definição.</p>{error&&<p role="alert">{error}</p>}{loading&&<p role="status">Verificando rascunhos…</p>}
 <form className="space-y-3" onSubmit={e=>{e.preventDefault();void save()}}><label className="block">Título do rascunho<Input required maxLength={120} value={title} disabled={blocked} onChange={e=>setTitle(e.target.value)}/></label>{select<DraftInput['referrals']>('Indicações',ref,referrals,setRef)}<p className="rounded border border-lime-400 bg-lime-50 p-3">Regra aprovada do PRO PARCEIRO: teto de 150 serviços. 10 contam como 10; 200 contam como 150.</p>{select<DraftInput['rating']>('Avaliação',rating,ratings,setRating)}{select<DraftInput['poolBasis']>('Base proposta para o cashback',basis,bases,setBasis)}<label className="block">Justificativa<textarea className="block w-full rounded border p-2" maxLength={2000} value={notes} disabled={blocked} onChange={e=>setNotes(e.target.value)}/></label><Button type="submit" disabled={blocked||!title.trim()||!ref||!rating||!basis}>Salvar somente rascunho</Button></form>
 {ref&&rating&&<div className="overflow-x-auto"><p>Comparação fictícia: multiplicador 2, 3 indicações, avaliação 4,5 e 12 meses. Pontos deste mês; serviços elegíveis e indicações reais ainda precisam de validação.</p><table className="w-full text-sm"><caption>Regra aprovada: teto de 150 serviços</caption><thead><tr><th>Regra</th><th>10 serviços</th><th>200 serviços</th></tr></thead><tbody><tr><th>Teto de 150 serviços</th><td>{example(ref,rating,10)}</td><td>{example(ref,rating,200)}</td></tr></tbody></table></div>}
 <EsgCashbackSimulator disabled={disabled||saving}/>
 <h3 className="font-semibold">Histórico de rascunhos</h3>{loadedOwner===owner&&(rows.length?<ul className="space-y-2">{rows.map(row=><li className="rounded border p-3" key={row.id}><p className="font-semibold">{row.title}</p>{row.partner_services!==APPROVED_PARTNER_SERVICES&&<p>Histórico: regra de serviços anterior à decisão aprovada.</p>}<p>Rascunho — {new Date(row.created_at).toLocaleString('pt-BR')}</p><p className="break-all text-xs">Versão {row.id}</p><p>{referrals[row.referrals]}; {services[row.partner_services]}; {ratings[row.rating]}; {bases[row.pool_basis]}.</p>{row.notes&&<p className="whitespace-pre-wrap">{row.notes}</p>}</li>)}</ul>:<p>Nenhum rascunho nesta página.</p>)}<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={blocked||page<=1} onClick={()=>setPage(n=>n-1)}>Anterior</Button><span>Página {page}</span><Button type="button" variant="outline" disabled={blocked||rows.length<20||page>=10000} onClick={()=>setPage(n=>n+1)}>Próxima</Button><Button type="button" variant="outline" disabled={disabled||loading||saving} onClick={()=>setReload(n=>n+1)}>Atualizar histórico</Button></div>
 </section>
}
