import BookingSlotReview from '@/components/BookingSlotReview'
import type {BookingSlot} from '@/lib/supabase/bookingQuote'
import BookingTerms from '@/components/BookingTerms'
import {useEffect,useState} from 'react'
import {Button} from '@/components/ui/button'
import {readReleasedAvailability,saoPauloToday,shiftMonth,type ReleasedDay} from '@/lib/supabase/availability'
export default function ReleasedAvailability({owner,professionalId,disabled}:{owner:string;professionalId:string;disabled:boolean}){
 const [selected,setSelected]=useState<BookingSlot|null>(null)
 const first=saoPauloToday().slice(0,8)+'01',[month,setMonth]=useState(first),[rows,setRows]=useState<ReleasedDay[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[reload,setReload]=useState(0)
 useEffect(()=>{let active=true;setRows([]);setSelected(null);setError('');setLoading(true);void readReleasedAvailability(professionalId,month,owner).then(result=>{if(active)setRows(result)}).catch(()=>{if(active)setError('Não foi possível verificar os horários.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[owner,professionalId,month,reload])
 return <section className="space-y-2 rounded border p-3" aria-label="Horários liberados"><h3 className="font-semibold">Horários liberados pelo profissional</h3><BookingTerms key={owner+professionalId} owner={owner} professionalId={professionalId} disabled={disabled}/><p>Horário de Brasília. Consulta de disponibilidade; agendamento e pagamento do sinal ainda não estão disponíveis.</p><div className="flex flex-wrap items-center gap-2"><Button type="button" variant="outline" disabled={disabled||loading||month<=first} onClick={()=>setMonth(shiftMonth(month,-1))}>Mês anterior</Button><span>{new Date(month+'T12:00:00Z').toLocaleDateString('pt-BR',{month:'long',year:'numeric',timeZone:'America/Sao_Paulo'})}</span><Button type="button" variant="outline" disabled={disabled||loading||month>=shiftMonth(first,12)} onClick={()=>setMonth(shiftMonth(month,1))}>Próximo mês</Button></div>{loading?<p role="status">Verificando horários…</p>:error?<p role="alert">{error}</p>:rows.length?<ul>{rows.map(row=><li key={row.day}><strong>{new Date(row.day+'T12:00:00Z').toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'})}</strong>: <div className="flex flex-wrap gap-2">{row.available_hours.map(hour=><Button type="button" variant="outline" key={hour} disabled={disabled||loading} aria-pressed={selected?.day===row.day&&selected.hour===hour} onClick={()=>setSelected({professionalId,day:row.day,hour})}>Conferir {String(hour).padStart(2,'0')}:00</Button>)}</div></li>)}</ul>:<p>Nenhum horário liberado neste mês.</p>}{!loading&&!error&&selected&&selected.day.startsWith(month.slice(0,7))&&<BookingSlotReview key={[owner,selected.professionalId,selected.day,selected.hour].join(':')} owner={owner} slot={selected} disabled={disabled} onClose={()=>setSelected(null)}/>}<Button type="button" variant="outline" disabled={disabled||loading} onClick={()=>setReload(n=>n+1)}>Atualizar horários</Button></section>
}
